; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_nesdev_2023=music_data_nesdev_2023
.endif

music_data_nesdev_2023:
	.byte 3
	.word @instruments
	.word @instruments_exp
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7 ; 00 : EPSM Detected
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6,@song1ch7 ; 01 : Intro
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6,@song2ch7 ; 02 : Title Ambience
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_nesdev_2023
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env15,@env27,@env29,@env0 ; 00 : Pluck 1 D1
	.word @env15,@env27,@env34,@env0 ; 01 : Pluck 1 D2
	.word @env15,@env27,@env22,@env0 ; 02 : Pluck 1 D3
	.word @env13,@env11,@env16,@env0 ; 03 : Pluck 3
	.word @env21,@env20,@env16,@env0 ; 04 : Snare
	.word @env8,@env1,@env16,@env0 ; 05 : Hi Hat 1
	.word @env5,@env1,@env16,@env0 ; 06 : Hi Hat
	.word @env4,@env11,@env17,@env0 ; 07 : Pluck 2
	.word @env9,@env11,@env16,@env32 ; 08 : Tri Vib
	.word @env6,@env1,@env18,@env0 ; 09 : Hi Hat 2
	.word @env10,@env23,@env16,@env0 ; 0a : Snare 1
	.word @env19,@env33,@env18,@env0 ; 0b : Snare 2
	.word @env12,@env30,@env14,@env0 ; 0c : Ambient Noise 1
	.word @env24,@env3,@env7,@env0 ; 0d : Ambient Noise
	.word @env31,@env25,@env2,@env0 ; 0e : Soft 6

@instruments_exp:
	.word @env26, @env11, @env0 ; 00 : Saw R
	.word @env28, @env11
	.word @instrument_epsm_extra_patch0
	.byte $37,$40,$60,$00
	.word @env26, @env11, @env0 ; 01 : Saw L
	.word @env28, @env11
	.word @instrument_epsm_extra_patch1
	.byte $37,$80,$60,$00
	.word @env9, @env11, @env0 ; 02 : Soft Bass
	.word @env28, @env11
	.word @instrument_epsm_extra_patch2
	.byte $3d,$c0,$00,$1e
	.word @env9, @env11, @env0 ; 03 : Evil 2
	.word @env28, @env11
	.word @instrument_epsm_extra_patch7
	.byte $04,$d0,$62,$14
	.word @env9, @env11, @env0 ; 04 : Bell R
	.word @env28, @env11
	.word @instrument_epsm_extra_patch8
	.byte $04,$50,$0f,$14
	.word @env9, @env11, @env0 ; 05 : Bell L
	.word @env28, @env11
	.word @instrument_epsm_extra_patch9
	.byte $04,$90,$0f,$14
	.word @env9, @env11, @env0 ; 06 : Evil R
	.word @env28, @env11
	.word @instrument_epsm_extra_patch16
	.byte $24,$40,$62,$08
	.word @env9, @env11, @env0 ; 07 : Evil L
	.word @env28, @env11
	.word @instrument_epsm_extra_patch17
	.byte $24,$80,$22,$08
	.word @env9, @env11, @env0 ; 08 : Evil 3
	.word @env28, @env11
	.word @instrument_epsm_extra_patch20
	.byte $24,$c0,$71,$08
	.word @env9, @env11, @env0 ; 09 : Noise 1
	.word @env28, @env11
	.word @instrument_epsm_extra_patch23
	.byte $3c,$80,$0f,$00
	.word @env9, @env11, @env0 ; 0a : Noise
	.word @env28, @env11
	.word @instrument_epsm_extra_patch24
	.byte $34,$40,$0f,$00
	.word @env9, @env11, @env0 ; 0b : Evil LR
	.word @env28, @env11
	.word @instrument_epsm_extra_patch26
	.byte $24,$c0,$62,$08

@instrument_epsm_extra_patch0:
	.byte $1f,$00,$00,$0c,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch1:
	.byte $1f,$00,$00,$0c,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch2:
	.byte $1f,$0b,$00,$ff,$00,$30,$1e,$1f,$09,$00,$f9,$00,$70,$22,$1f,$00,$00,$0f,$00,$00,$1e,$11,$1f,$00,$07,$00,$00
@instrument_epsm_extra_patch7:
	.byte $1f,$1f,$00,$00,$00,$02,$23,$0b,$1f,$00,$04,$00,$32,$12,$1f,$1f,$00,$00,$00,$12,$23,$0b,$1f,$00,$04,$00,$00
@instrument_epsm_extra_patch8:
	.byte $1f,$1f,$08,$02,$00,$2d,$26,$1f,$1f,$06,$03,$00,$7a,$10,$1f,$1f,$06,$03,$00,$17,$26,$1f,$1f,$05,$03,$00,$00
@instrument_epsm_extra_patch9:
	.byte $1f,$1f,$08,$02,$00,$2d,$22,$1f,$1f,$06,$03,$00,$7a,$10,$1f,$1f,$06,$03,$00,$17,$22,$1f,$1f,$05,$03,$00,$00
@instrument_epsm_extra_patch16:
	.byte $04,$1f,$05,$09,$00,$02,$26,$1f,$1f,$00,$09,$00,$33,$08,$04,$1f,$05,$09,$00,$03,$2a,$1f,$1f,$00,$09,$00,$00
@instrument_epsm_extra_patch17:
	.byte $04,$1f,$05,$09,$00,$02,$26,$1f,$1f,$00,$09,$00,$73,$08,$04,$1f,$05,$09,$00,$03,$2a,$1f,$1f,$00,$09,$00,$00
@instrument_epsm_extra_patch20:
	.byte $04,$1f,$05,$04,$00,$01,$23,$1f,$1f,$00,$04,$00,$3f,$0b,$04,$1f,$05,$04,$00,$00,$2c,$1f,$1f,$00,$03,$00,$00
@instrument_epsm_extra_patch23:
	.byte $1f,$00,$00,$0f,$00,$00,$37,$07,$00,$00,$0f,$00,$30,$7f,$1f,$00,$00,$07,$00,$31,$33,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch24:
	.byte $1f,$00,$00,$0f,$00,$00,$37,$07,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$07,$00,$70,$33,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch26:
	.byte $04,$1f,$05,$09,$00,$02,$26,$1f,$1f,$00,$09,$00,$33,$08,$04,$1f,$05,$09,$00,$03,$2a,$1f,$1f,$00,$09,$00,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $c2,$06,$c1,$00,$02
@env3:
	.byte $c0,$2a,$bd,$c0,$29,$bf,$0a,$c1,$1a,$c5,$c1,$1f,$bf,$c0,$2f,$c2,$c0,$c2,$c0,$20,$bf,$c0,$0b,$c0,$00,$00
@env4:
	.byte $07,$c6,$c7,$c7,$c6,$00,$04,$c0,$c7,$c7,$c6,$00,$0a
@env5:
	.byte $00,$ce,$c3,$c1,$c0,$00,$04
@env6:
	.byte $00,$cb,$c3,$c0,$00,$03
@env7:
	.byte $c0,$27,$c1,$c0,$6e,$c1,$c0,$4a,$c1,$c0,$08,$c1,$c0,$06,$c0,$00,$00
@env8:
	.byte $00,$c5,$c1,$c0,$00,$03
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $00,$cb,$c8,$c6,$c5,$c5,$c4,$0a,$c3,$00,$08
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $00,$c0,$02,$c1,$0f,$c2,$07,$c2,$07,$c3,$19,$c4,$26,$c3,$20,$c2,$29,$c3,$0e,$c2,$1b,$c2,$00,$07
@env13:
	.byte $12,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c5,$00,$0f,$c4,$03,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$1a
@env14:
	.byte $c0,$20,$c1,$3e,$c0,$37,$c2,$3c,$c0,$0e,$c1,$11,$c1,$00,$00
@env15:
	.byte $07,$c8,$c9,$c9,$c8,$00,$04,$c7,$c5,$c5,$c4,$00,$0a
@env16:
	.byte $7f,$00,$00
@env17:
	.byte $c1,$08,$c0,$00,$02
@env18:
	.byte $c1,$7f,$00,$00
@env19:
	.byte $00,$c3,$10,$c2,$0f,$c1,$00,$05
@env20:
	.byte $bc,$c2,$c0,$00,$02
@env21:
	.byte $00,$cb,$c8,$c6,$c5,$c5,$c4,$03,$c3,$06,$c2,$03,$c1,$00,$0c
@env22:
	.byte $c2,$07,$c1,$00,$02
@env23:
	.byte $bb,$bd,$bd,$be,$bf,$bf,$bf,$c0,$c0,$00,$06
@env24:
	.byte $00,$c1,$7f,$00,$02
@env25:
	.byte $c0,$c7,$00,$00
@env26:
	.byte $00,$c8,$7f,$00,$02
@env27:
	.byte $b4,$c0,$08,$cc,$03,$c0,$00,$05
@env28:
	.byte $c8,$7f,$00,$00
@env29:
	.byte $c0,$07,$c2,$00,$02
@env30:
	.byte $c0,$2a,$d8,$d8,$c0,$4a,$cc,$cc,$c0,$0d,$d8,$d8,$c0,$36,$cc,$d8,$d8,$c0,$2d,$cc,$c0,$0b,$c0,$00,$00
@env31:
	.byte $00,$c2,$02,$c0,$02,$c1,$00,$05
@env32:
	.byte $00,$c0,$1a,$c0,$c0,$c1,$c2,$02,$c1,$c0,$c0,$bf,$be,$02,$bf,$00,$03
@env33:
	.byte $c6,$c3,$c1,$bf,$be,$bd,$bb,$ba,$b9,$b9,$b8,$b7,$b6,$b5,$b5,$b4,$00,$00
@env34:
	.byte $c1,$07,$c2,$00,$02

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $df
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $df
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $df
@song0ch2loop:
	.byte $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $df
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $df
@song0ch4loop:
	.byte $00, $42
	.word @song0ch4loop
@song0ch5:
	.byte $80, $40, $54, $8b, $40, $57, $8b, $40, $5c, $8b, $00, $a7, $40, $5c, $85, $00, $83, $40, $5c, $83, $00, $f5
@song0ch5loop:
	.byte $00, $42
	.word @song0ch5loop
@song0ch6:
	.byte $82, $40, $50, $8b, $40, $54, $8b, $40, $57, $8b, $00, $d1, $40, $57, $83, $00, $85, $40, $57, $85, $00, $c9
@song0ch6loop:
	.byte $00, $42
	.word @song0ch6loop
@song0ch7:
	.byte $84, $24, $8b, $2c, $8b, $30, $8d, $00, $f9, $20, $85, $00, $83, $20, $8b, $5a, $8b, $00, $8b
@song0ch7loop:
	.byte $00, $42
	.word @song0ch7loop
@song1ch0:
@song1ref1:
	.byte $80
@song1ref2:
	.byte $16, $8b, $44, $81, $43, $11, $8f, $82, $1d, $8b, $44, $81, $43, $16, $8f, $84, $19, $8b, $44, $81, $43, $1d, $8f, $80
	.byte $11, $8b, $44, $81, $43, $19, $8f, $82, $12, $8b, $44, $81, $43, $11, $8f, $84, $1d, $8b, $44, $81, $43, $12, $8f, $82
	.byte $12, $8b, $44, $81, $43, $1d, $8f, $47
	.byte $41, $2a
	.word @song1ref1
@song1ref61:
	.byte $47, $84, $16, $8b, $44, $81, $43, $10, $8f, $82, $1c, $8b, $44, $81, $43, $16, $8f, $80, $19, $8b, $44, $81, $43, $1c
	.byte $8f, $84, $10, $8b, $44, $81, $43, $19, $8f, $13, $8b, $44, $81, $43, $10, $8f, $82, $1c, $8b, $44, $81, $43, $13, $8f
	.byte $80, $13, $8b, $44, $81, $43, $1c, $8f
	.byte $41, $2a
	.word @song1ref61
	.byte $47
	.byte $41, $2a
	.word @song1ref2
	.byte $47
	.byte $41, $2a
	.word @song1ref1
	.byte $41, $2a
	.word @song1ref61
	.byte $41, $2a
	.word @song1ref61
	.byte $47
	.byte $41, $2a
	.word @song1ref2
	.byte $47
	.byte $41, $2a
	.word @song1ref1
	.byte $41, $2a
	.word @song1ref61
	.byte $41, $2a
	.word @song1ref61
	.byte $47, $8e
@song1ref150:
	.byte $16, $8d, $44, $43, $40, $0a, $8f, $1d, $8d, $44, $43, $40, $0a, $8f, $19, $8d, $44, $43, $40, $0a, $8f, $11, $8d, $44
	.byte $43, $40, $0a, $8f, $12, $8d, $44, $43, $40, $0a, $8f, $1d, $8d, $44, $43, $40, $0a, $8f, $12, $8d, $44, $43, $40, $0a
	.byte $8f, $47
	.byte $41, $23
	.word @song1ref150
@song1ref203:
	.byte $47, $16, $8d, $44, $43, $04, $8f, $1c, $8d, $44, $43, $04, $8f, $19, $8d, $44, $43, $04, $8f, $10, $8d, $44, $43, $04
	.byte $8f, $13, $8d, $44, $43, $04, $8f, $1c, $8d, $44, $43, $04, $8f, $13, $8d, $44, $43, $04, $8f
	.byte $41, $17
	.word @song1ref203
	.byte $43, $07, $8f, $1c, $8d, $44, $43, $04, $8f, $13, $8d, $44, $43, $04, $8f, $47
	.byte $41, $23
	.word @song1ref150
	.byte $47
	.byte $41, $23
	.word @song1ref150
	.byte $41, $23
	.word @song1ref203
	.byte $41, $14
	.word @song1ref203
	.byte $47, $13, $8f, $44, $43, $07, $8f, $47, $1c, $8f, $44, $43, $04, $91, $47, $13, $91, $44, $43, $04, $93, $47, $00, $ff
	.byte $ff, $ff, $ff, $ff, $bd
@song1ch0loop:
	.byte $00, $42
	.word @song1ch0loop
@song1ch1:
	.byte $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $86
@song1ref321:
	.byte $40, $0a, $8f, $44, $a1
@song1ref326:
	.byte $40, $0a, $8f, $44, $a1, $40, $0a, $8f, $44, $a1, $40, $0a, $8f, $44, $a1, $40, $0a, $8f, $44, $8f, $91
	.byte $41, $10
	.word @song1ref326
@song1ref350:
	.byte $40, $0a, $89, $44, $83, $40, $0a, $89, $44, $83, $04, $8f, $44, $a1, $04, $8f, $44, $a1, $04, $8f, $44, $a1, $04, $8f
	.byte $44, $a1, $04, $8f, $44, $8f, $91, $04, $8f, $44, $a1, $04, $8f, $44, $a1, $04, $8f, $07, $a1, $04, $c5
	.byte $41, $15
	.word @song1ref321
	.byte $41, $10
	.word @song1ref326
	.byte $41, $28
	.word @song1ref350
	.byte $87, $44, $85, $07, $87, $44, $85, $04, $99, $44, $85, $04, $99, $44, $85, $4d, $06
	.byte $41, $15
	.word @song1ref321
	.byte $41, $10
	.word @song1ref326
	.byte $41, $28
	.word @song1ref350
	.byte $87, $44, $85, $07, $87, $44, $85, $04, $99, $44, $85, $04, $99, $44, $85, $4d, $06
	.byte $41, $15
	.word @song1ref321
	.byte $41, $10
	.word @song1ref326
	.byte $41, $28
	.word @song1ref350
	.byte $89, $44, $85, $07, $87, $44, $85, $04, $9d, $44, $85, $04, $9f, $44, $87, $40, $0b, $ff, $81, $43, $4f, $b9, $0b, $14
	.byte $a9, $43, $08, $ff, $ff, $85, $44, $d5, $00, $ff, $ad
@song1ch1loop:
	.byte $00, $42
	.word @song1ch1loop
@song1ch2:
	.byte $86
@song1ref497:
	.byte $0a, $ff, $f9, $43, $0a, $ff, $d5, $43, $4f, $1c, $16, $14, $8f, $43, $4f, $42, $14, $10, $8f, $43, $04, $ff, $f9, $43
	.byte $04, $ff, $f9
	.byte $41, $10
	.word @song1ref497
	.byte $41, $10
	.word @song1ref497
	.byte $90, $2e, $ff, $b1, $31, $c5, $30, $ff, $b1, $2d, $c5, $31, $ff, $d5, $30, $8f, $2f, $8f, $2e, $ff, $f9, $2e, $ff, $b1
	.byte $31, $c5, $30, $ff, $b1, $2d, $c5, $2c, $c5, $34, $ff, $8d, $31, $8f, $33, $8f, $34, $ff, $8d, $37, $9d, $00, $83, $37
	.byte $9f, $00, $83, $37, $a1, $00, $85, $37, $93, $38, $ff, $81, $43, $4f, $0c, $44, $39, $93, $08, $ff, $ff, $85, $00, $ff
	.byte $ff, $85
@song1ch2loop:
	.byte $00, $42
	.word @song1ch2loop
@song1ch3:
	.byte $ff, $fb, $ff, $fb
@song1ref613:
	.byte $88, $34, $85, $00, $87, $8a, $32, $85, $00, $99, $32, $87, $00, $85, $8c, $32, $85, $00, $99, $8a, $32, $85, $00, $87
	.byte $8c, $32, $85, $00, $99, $8a, $32, $87, $00, $85, $8c, $32, $85, $00, $99, $32, $85, $00, $87, $8a, $32, $87, $00, $85
	.byte $41, $28
	.word @song1ref613
@song1ref664:
	.byte $88, $34, $85, $00, $87, $8a, $32, $85, $00, $99, $32, $87, $00, $85, $8c, $32, $85, $8a, $31, $87, $32, $87, $00, $85
	.byte $32, $85, $00, $87, $8c, $32, $85, $00, $99, $8a, $32, $87, $00, $85, $8c, $32, $85, $00, $87, $8a, $32, $87, $8c, $32
	.byte $85, $31, $83, $00, $83, $32, $83, $00, $83, $32, $83, $00, $83
	.byte $41, $34
	.word @song1ref664
	.byte $41, $34
	.word @song1ref664
	.byte $41, $1b
	.word @song1ref664
	.byte $87, $30, $85, $00, $87, $8a, $31, $87, $00, $85, $32, $85, $00, $87, $8c, $31, $87, $00, $85, $8a, $31, $85, $00, $87
	.byte $32, $87, $00, $85
	.byte $41, $34
	.word @song1ref664
	.byte $41, $34
	.word @song1ref664
	.byte $41, $34
	.word @song1ref664
	.byte $41, $20
	.word @song1ref664
	.byte $8c, $31, $85, $00, $81, $8a, $32, $83, $00, $83, $32, $83, $00, $83, $8c, $31, $85, $00, $81, $8a, $32, $83, $00, $83
@song1ref798:
	.byte $32, $83, $00, $83, $88, $34, $85, $00, $87, $8a, $32, $85, $00, $87, $92, $30, $8f, $8a, $32, $87, $00, $85, $88, $2d
	.byte $8f, $8a, $32, $87, $00, $85, $92, $30, $8f, $30, $8f, $00, $8f, $8a, $32, $87, $00, $85, $8c, $32, $85, $00, $87, $8a
	.byte $32, $87, $32, $85, $88, $31, $89, $8a, $32, $83, $92, $30, $83, $8a
	.byte $41, $30
	.word @song1ref798
	.byte $8a
	.byte $41, $30
	.word @song1ref798
	.byte $8a
	.byte $41, $2a
	.word @song1ref798
	.byte $88, $2e, $89, $8a, $32, $83, $88, $2e, $83, $8a
	.byte $41, $30
	.word @song1ref798
	.byte $8a
	.byte $41, $30
	.word @song1ref798
	.byte $8a
	.byte $41, $30
	.word @song1ref798
	.byte $8a
	.byte $41, $1c
	.word @song1ref798
	.byte $88, $2c, $91, $8a, $32, $87, $00, $85, $88, $2c, $91, $8a, $32, $89, $32, $85, $88, $2c, $8b, $8a, $32, $85, $88, $2e
	.byte $83, $8a, $32, $85, $00, $85, $94, $2f, $a9, $43, $4f, $fc, $3b, $34, $bf, $43, $4f, $f2, $34, $21, $a9, $43, $4f, $e5
	.byte $21, $0f, $93, $96, $40, $0c, $ff, $99, $00, $ff, $ff, $f1
@song1ch3loop:
	.byte $00, $42
	.word @song1ch3loop
@song1ch4:
	.byte $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb
	.byte $51, $8e, $91, $51, $9c, $91, $51, $ac, $91, $51, $c2, $ff, $c5, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff
	.byte $fb, $ff, $8f, $a5, $a7, $ab, $ff, $ff, $ff, $ff, $ff, $bf
@song1ch4loop:
	.byte $00, $42
	.word @song1ch4loop
@song1ch5:
	.byte $86
@song1ref1027:
	.byte $40, $0a, $ff, $f9, $ff, $d7, $43, $4f, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $fb, $40, $0a, $ff, $f9, $ff
	.byte $d7, $43, $4f, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $fb
	.byte $41, $18
	.word @song1ref1027
	.byte $40, $0a, $ff, $f9, $ff, $d7, $43, $4f, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $8f, $a5, $a7, $ab, $40, $07
	.byte $93, $43, $40, $08, $ff, $ff, $dd, $5a, $ff, $ff, $9b, $00, $a9
@song1ch5loop:
	.byte $00, $42
	.word @song1ch5loop
@song1ch6:
	.byte $88, $40, $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $40, $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $40
	.byte $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $8c
@song1ref1145:
	.byte $0a, $ff, $f9, $ff, $d7, $43, $4f, $ff, $16, $14, $8f, $43, $4f, $fe, $14, $10, $8f, $43, $04, $ff, $f9, $ff, $f5, $5a
	.byte $83, $0a, $ff, $f9, $ff, $d7, $43, $4f, $ff, $16, $14, $8f, $43, $4f, $fe, $14, $10, $8f, $43, $04, $ff, $f9, $ff, $8f
	.byte $a5, $a7, $a1, $5a, $83, $00, $81, $ff, $ff, $ff, $ff, $ff, $bf
@song1ch6loop:
	.byte $00, $42
	.word @song1ch6loop
@song1ch7:
@song1ref1211:
	.byte $8a, $40, $01, $ff, $f9, $ff, $fb, $84, $10, $97, $5a, $99, $10, $97, $5a, $99, $10, $97, $5a, $99, $10, $97, $5a, $99
	.byte $10, $97, $5a, $87, $91, $10, $97, $5a, $99, $10, $97, $5a, $99, $10, $8f, $10, $8f, $5a, $8f, $10, $8f, $5a, $8f, $10
	.byte $8f, $5a, $8f
	.byte $41, $30
	.word @song1ref1211
	.byte $41, $30
	.word @song1ref1211
	.byte $8e
	.byte $41, $25
	.word @song1ref1145
	.byte $90, $08, $ff, $ff, $ff, $b5, $5a, $ff, $d9, $00, $a9
@song1ch7loop:
	.byte $00, $42
	.word @song1ch7loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $df, $47, $ff, $ff, $df, $47, $9c
@song2ref14:
	.byte $18, $93, $00, $bf, $18, $93, $00, $bf, $18, $93, $00, $bf, $18, $93, $00, $bf, $47, $ff, $ff, $df, $47, $ff, $ff, $df
	.byte $47, $ff, $ff, $df, $47, $ff, $ff, $df, $47
	.byte $41, $19
	.word @song2ref14
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $98, $40, $0b
@song2ref57:
	.byte $ff, $ff, $dd
@song2ref60:
	.byte $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df
	.byte $ff, $ff, $df, $ff, $ff, $df, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $41, $1e
	.word @song2ref60
	.byte $ff, $ff, $df, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $9a, $05
	.byte $41, $21
	.word @song2ref57
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $1e
	.word @song2ref60
	.byte $ff, $ff, $df, $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $ff, $ff, $df, $ff, $ff, $df, $96, $18, $99, $5a, $97, $00, $9f, $18, $99, $5a, $97, $00, $9f, $18, $99, $5a, $97, $00
	.byte $9f, $18, $99, $5a, $97, $00, $9f, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df, $90, $07, $ff, $ff, $dd
	.byte $87, $5a, $ff, $ff, $d5, $00, $ff, $ff, $dd, $ff, $ff, $df, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $92, $17
	.byte $41, $21
	.word @song2ref57
	.byte $42
	.word @song2ch6loop
@song2ch7:
@song2ch7loop:
	.byte $94, $22
	.byte $41, $21
	.word @song2ref57
	.byte $42
	.word @song2ch7loop
