; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_EXP_EPSM
.ifndef FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT
FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT = 3
.endif
.ifndef FAMISTUDIO_EXP_EPSM_FM_CHN_CNT
FAMISTUDIO_EXP_EPSM_FM_CHN_CNT = 6
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE = 1
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE = 1
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE = 1
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE = 1
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE = 1
.endif
.ifndef FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE = 1
.endif
.endif
.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
.endif
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
.endif
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
.endif

	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:

@instruments_exp:
	.word @env1, @env2, @env0 ; 00 : Instrument 2
	.word @env4, @env2
	.word @instrument_epsm_extra_patch0
	.byte $04,$c0,$00,$20

@instrument_epsm_extra_patch0:
	.byte $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c8,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref72:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch4loop
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
@song0ch5:
@song0ch5loop:
	.byte $cf, $80, $1f, $cd, $00, $ff, $9d
	.byte $41, $2d
	.word @song0ref72
	.byte $42
	.word @song0ch5loop
.endif
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
@song0ch6:
@song0ch6loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch6loop
.endif
.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
@song0ch7:
@song0ch7loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch7loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
@song0ch8:
@song0ch8loop:
	.byte $cf, $80, $25, $cd, $00, $ff, $9d
	.byte $41, $2d
	.word @song0ref72
	.byte $42
	.word @song0ch8loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
@song0ch9:
@song0ch9loop:
	.byte $ff, $ef, $80, $20, $cd, $00, $ff, $ff, $bd
	.byte $41, $2a
	.word @song0ref72
	.byte $42
	.word @song0ch9loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
@song0ch10:
@song0ch10loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch10loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
@song0ch11:
@song0ch11loop:
	.byte $ff, $9f, $80, $27, $cd, $00, $cd
	.byte $41, $2d
	.word @song0ref72
	.byte $42
	.word @song0ch11loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
@song0ch12:
@song0ch12loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch12loop
.endif
.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
@song0ch13:
@song0ch13loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch13loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
@song0ch14:
@song0ch14loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch14loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
@song0ch15:
@song0ch15loop:
	.byte $ff, $9f, $80, $1d, $cd, $00, $cd
	.byte $41, $2d
	.word @song0ref72
	.byte $42
	.word @song0ch15loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
@song0ch16:
@song0ch16loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch16loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
@song0ch17:
@song0ch17loop:
	.byte $80, $25, $cd, $25, $cd, $25, $cd, $25, $cd, $00, $ff, $ff, $bd
	.byte $41, $2a
	.word @song0ref72
	.byte $42
	.word @song0ch17loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
@song0ch18:
@song0ch18loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch18loop
.endif
.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
@song0ch19:
@song0ch19loop:
	.byte $41, $30
	.word @song0ref72
	.byte $42
	.word @song0ch19loop
.endif
