; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_untitled:
	.db 1
	.dw .instruments
	.dw .instruments_exp
	.dw .samples-4
; 00 : Song 1
	.dw .song0ch0
	.dw .song0ch1
	.dw .song0ch2
	.dw .song0ch3
	.dw .song0ch4
IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.dw .song0ch5
ENDIF
IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.dw .song0ch6
ENDIF
IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.dw .song0ch7
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.dw .song0ch8
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.dw .song0ch9
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.dw .song0ch10
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.dw .song0ch11
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.dw .song0ch12
ENDIF
IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.dw .song0ch13
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.dw .song0ch14
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.dw .song0ch15
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.dw .song0ch16
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.dw .song0ch17
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.dw .song0ch18
ENDIF
IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.dw .song0ch19
ENDIF

	.db LOW(.tempo_env_1_mid), HIGH(.tempo_env_1_mid), 0, 0

.instruments:

.instruments_exp:
	.dw .env1, .env2, .env0 ; 00 : Instrument 2
	.dw .env4, .env2
	.dw .instrument_epsm_extra_patch0
	.db $04,$c0,$00,$20

.instrument_epsm_extra_patch0:
	.db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00

.env0:
	.db $00,$c0,$7f,$00,$02
.env1:
	.db $00,$cf,$7f,$00,$02
.env2:
	.db $c0,$7f,$00,$01
.env3:
	.db $7f,$00,$00
.env4:
	.db $c8,$7f,$00,$00

.samples:

.tempo_env_1_mid:
	.db $03,$05,$80

.song0ch0:
.song0ch0loop:
	.db $46, LOW(.tempo_env_1_mid), HIGH(.tempo_env_1_mid), $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff
	.db $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff
	.db $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff
	.db $bf, $42
	.dw .song0ch0loop
.song0ch1:
.song0ch1loop:
.song0ref72:
	.db $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.db $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.db $42
	.dw .song0ch1loop
.song0ch2:
.song0ch2loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch2loop
.song0ch3:
.song0ch3loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch3loop
.song0ch4:
.song0ch4loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch4loop
	.db IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0

.song0ch5:
.song0ch5loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch5loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1

.song0ch6:
.song0ch6loop:
	.db $ff, $9f, $80, $24, $cd, $00, $cd
	.db $41, $2d
	.dw .song0ref72
	.db $42
	.dw .song0ch6loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2

.song0ch7:
.song0ch7loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch7loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0

.song0ch8:
.song0ch8loop:
	.db $cf, $80, $27, $cd, $00, $ff, $9d
	.db $41, $2d
	.dw .song0ref72
	.db $42
	.dw .song0ch8loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1

.song0ch9:
.song0ch9loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch9loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2

.song0ch10:
.song0ch10loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch10loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3

.song0ch11:
.song0ch11loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch11loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4

.song0ch12:
.song0ch12loop:
	.db $cf, $80, $26, $cd, $00, $ff, $9d
	.db $41, $2d
	.dw .song0ref72
	.db $42
	.dw .song0ch12loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5

.song0ch13:
.song0ch13loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch13loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE

.song0ch14:
.song0ch14loop:
	.db $ff, $9f, $80, $22, $cd, $00, $cd
	.db $41, $2d
	.dw .song0ref72
	.db $42
	.dw .song0ch14loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE

.song0ch15:
.song0ch15loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch15loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE

.song0ch16:
.song0ch16loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch16loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE

.song0ch17:
.song0ch17loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch17loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE

.song0ch18:
.song0ch18loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch18loop
	.db ENDIF, IF FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE

.song0ch19:
.song0ch19loop:
	.db $41, $30
	.dw .song0ref72
	.db $42
	.dw .song0ch19loop
