; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_oddity=music_data_oddity
.endif

music_data_oddity:
	.byte 4
	.word @instruments
	.word @instruments_exp
	.word @samples-4
; 00 : Intro
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song0ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song0ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song0ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song0ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song0ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song0ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song0ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song0ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song0ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song0ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song0ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song0ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song0ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song0ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song0ch19
	.endif
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Dangerous Citty
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song1ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song1ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song1ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song1ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song1ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song1ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song1ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song1ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song1ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song1ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song1ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song1ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song1ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song1ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song1ch19
	.endif
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Dangerous Citty Battle
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song2ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song2ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song2ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song2ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song2ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song2ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song2ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song2ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song2ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song2ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song2ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song2ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song2ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song2ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song2ch19
	.endif
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Boss
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 0
	.word @song3ch5
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 1
	.word @song3ch6
	.endif
	.if FAMISTUDIO_EXP_EPSM_SSG_CHN_CNT > 2
	.word @song3ch7
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 0
	.word @song3ch8
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 1
	.word @song3ch9
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 2
	.word @song3ch10
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 3
	.word @song3ch11
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 4
	.word @song3ch12
	.endif
	.if FAMISTUDIO_EXP_EPSM_FM_CHN_CNT > 5
	.word @song3ch13
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN1_ENABLE
	.word @song3ch14
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN2_ENABLE
	.word @song3ch15
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN3_ENABLE
	.word @song3ch16
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN4_ENABLE
	.word @song3ch17
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN5_ENABLE
	.word @song3ch18
	.endif
	.if FAMISTUDIO_EXP_EPSM_RHYTHM_CHN6_ENABLE
	.word @song3ch19
	.endif
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_oddity
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env18,@env1,@env31,@env0 ; 00 : Hi Hat 1
	.word @env52,@env51,@env31,@env0 ; 01 : Snare 1
	.word @env28,@env17,@env35,@env0 ; 02 : D2
	.word @env28,@env17,@env32,@env0 ; 03 : D3
	.word @env28,@env17,@env31,@env0 ; 04 : D1
	.word @env6,@env11,@env31,@env0 ; 05 : Snare Louder 3
	.word @env14,@env1,@env31,@env0 ; 06 : Hi Hat
	.word @env28,@env27,@env31,@env0 ; 07 : Pluck 3
	.word @env10,@env27,@env31,@env0 ; 08 : Vol 6
	.word @env40,@env47,@env31,@env0 ; 09 : Snare Louder
	.word @env38,@env37,@env31,@env0 ; 0a : Snare
	.word @env25,@env1,@env31,@env0 ; 0b : Hi Hat 4
	.word @env41,@env27,@env31,@env0 ; 0c : Hi Hat 3
	.word @env15,@env1,@env35,@env0 ; 0d : Hi Hat 2
	.word @env2,@env48,@env32,@env0 ; 0e : Arpy 3
	.word @env30,@env43,@env53,@env0 ; 0f : Pluck 1 D2
	.word @env30,@env43,@env39,@env0 ; 10 : Pluck 1 D3
	.word @env30,@env43,@env45,@env0 ; 11 : Pluck 1 D1
	.word @env24,@env27,@env31,@env0 ; 12 : Vol 9 R6
	.word @env2,@env3,@env32,@env0 ; 13 : Arpy 1
	.word @env54,@env33,@env31,@env0 ; 14 : Snare Louder 1
	.word @env26,@env33,@env31,@env0 ; 15 : Snare Louder 2
	.word @env50,@env55,@env31,@env0 ; 16 : Tri Bass
	.word @env19,@env13,@env31,@env0 ; 17 : Tri Bass 1
	.word @env29,@env22,@env32,@env46 ; 18 : Pluck 1
	.word @env19,@env27,@env31,@env46 ; 19 : Tri Vib
	.word @env42,@env49,@env9,@env0 ; 1a : ARP
	.word @env20,@env8,@env31,@env4 ; 1b : Tri Bass 2
	.word @env23,@env17,@env35,@env0 ; 1c : Pluck 1 D 1
	.word @env2,@env48,@env35,@env0 ; 1d : Arpy 6
	.word @env2,@env3,@env35,@env0 ; 1e : Arpy 4
	.word @env2,@env5,@env35,@env0 ; 1f : Arpy 5
	.word @env21,@env27,@env7,@env0 ; 20 : Bell
	.word @env36,@env16,@env31,@env0 ; 21 : Snare 2
	.word @env12,@env27,@env34,@env0 ; 22 : Pluck Echo

@instruments_exp:
	.word @env19, @env27, @env0 ; 00 : Soft Saw Bass
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch23
	.word @env19, @env27, @env0 ; 01 : Saw L
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch25
	.word @env19, @env27, @env0 ; 02 : Evil 1
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch26
	.word @env19, @env27, @env0 ; 03 : Saw R
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch27
	.word @env19, @env27, @env0 ; 04 : Bell L
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch28
	.word @env19, @env27, @env0 ; 05 : Evil 2
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch30
	.word @env19, @env27, @env0 ; 06 : Evil 3
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch32
	.word @env19, @env27, @env0 ; 07 : Screech
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch35
	.word @env19, @env27, @env0 ; 08 : Evil LR
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch36
	.word @env19, @env27, @env0 ; 09 : Evil L
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch41
	.word @env19, @env27, @env0 ; 0a : Bell R
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch44
	.word @env19, @env27, @env0 ; 0b : Evil R
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch45
	.word @env19, @env27, @env0 ; 0c : Saw R 1
	.word @env44, @env27
	.byte $00, $03
	.word 4000
	.word @instrument_epsm_extra_patch47

@instrument_epsm_extra_patch23:
	.byte $3d,$c0,$00,$1f,$0b,$00,$ff,$00,$30,$1f,$09,$00,$f9,$00,$70,$1f,$00,$00,$0f,$00,$00,$11,$1f,$00,$07,$00,$1e,$1e,$22,$1e,$00
@instrument_epsm_extra_patch25:
	.byte $37,$80,$30,$1f,$00,$00,$0c,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$14,$7f,$7f,$7f,$00
@instrument_epsm_extra_patch26:
	.byte $04,$d0,$62,$1f,$1f,$00,$00,$00,$02,$0b,$1f,$00,$04,$00,$32,$1f,$1f,$00,$00,$00,$12,$0b,$1f,$00,$04,$00,$14,$23,$12,$23,$00
@instrument_epsm_extra_patch27:
	.byte $37,$40,$70,$1f,$00,$00,$0c,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$14,$7f,$7f,$7f,$00
@instrument_epsm_extra_patch28:
	.byte $04,$90,$0f,$1f,$1f,$08,$02,$00,$2d,$1f,$1f,$06,$03,$00,$7a,$1f,$1f,$06,$03,$00,$17,$1f,$1f,$05,$03,$00,$14,$24,$10,$24,$00
@instrument_epsm_extra_patch30:
	.byte $04,$90,$62,$1f,$1f,$00,$00,$00,$02,$0b,$1f,$00,$04,$00,$32,$1f,$1f,$00,$00,$00,$12,$0b,$1f,$00,$04,$00,$14,$23,$12,$23,$00
@instrument_epsm_extra_patch32:
	.byte $04,$50,$62,$1f,$1f,$00,$00,$00,$02,$0b,$1f,$00,$04,$00,$32,$1f,$1f,$00,$00,$00,$12,$0b,$1f,$00,$04,$00,$14,$23,$12,$23,$00
@instrument_epsm_extra_patch35:
	.byte $24,$c0,$71,$04,$1f,$05,$04,$00,$01,$1f,$1f,$00,$04,$00,$3f,$04,$1f,$05,$04,$00,$00,$1f,$1f,$00,$03,$00,$08,$23,$0b,$2c,$00
@instrument_epsm_extra_patch36:
	.byte $24,$c0,$62,$04,$1f,$05,$09,$00,$02,$1f,$1f,$00,$09,$00,$33,$04,$1f,$05,$09,$00,$03,$1f,$1f,$00,$09,$00,$08,$26,$08,$2a,$00
@instrument_epsm_extra_patch41:
	.byte $24,$80,$22,$04,$1f,$05,$09,$00,$02,$1f,$1f,$00,$09,$00,$73,$04,$1f,$05,$09,$00,$03,$1f,$1f,$00,$09,$00,$08,$26,$08,$2a,$00
@instrument_epsm_extra_patch44:
	.byte $04,$50,$0f,$1f,$1f,$08,$02,$00,$2d,$1f,$1f,$06,$03,$00,$7a,$1f,$1f,$06,$03,$00,$17,$1f,$1f,$05,$03,$00,$14,$26,$10,$26,$00
@instrument_epsm_extra_patch45:
	.byte $24,$40,$62,$04,$1f,$05,$09,$00,$02,$1f,$1f,$00,$09,$00,$33,$04,$1f,$05,$09,$00,$03,$1f,$1f,$00,$09,$00,$08,$26,$08,$2a,$00
@instrument_epsm_extra_patch47:
	.byte $37,$40,$71,$1f,$00,$00,$0c,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$00,$1f,$00,$00,$0f,$00,$19,$7f,$7f,$7f,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $0e,$c9,$02,$c8,$02,$c7,$02,$c6,$02,$c5,$02,$c4,$00,$0b,$c3,$03,$c2,$02,$c1,$04,$c0,$00,$14
@env3:
	.byte $c0,$c0,$c5,$c5,$c8,$c8,$cc,$cc,$00,$00
@env4:
	.byte $80,$e4,$00,$01
@env5:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$cc,$cc,$00,$00
@env6:
	.byte $00,$cb,$c8,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$03,$c0,$00,$0d
@env7:
	.byte $c2,$c3,$00,$01
@env8:
	.byte $c7,$c5,$c3,$c1,$bf,$bd,$00,$05
@env9:
	.byte $c2,$05,$c1,$06,$c0,$07,$c1,$05,$c0,$03,$c2,$04,$c2,$00,$00
@env10:
	.byte $00,$c5,$7f,$00,$02
@env11:
	.byte $c9,$c3,$c0,$00,$02
@env12:
	.byte $07,$c6,$c7,$c7,$c6,$00,$04,$c7,$02,$c6,$00,$09
@env13:
	.byte $d8,$cc,$c0,$00,$02
@env14:
	.byte $00,$ce,$c3,$c1,$c0,$00,$04
@env15:
	.byte $00,$cb,$c3,$c0,$00,$03
@env16:
	.byte $b5,$b5,$b4,$b4,$c6,$c3,$c1,$bf,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$00
@env17:
	.byte $b4,$c0,$00,$01
@env18:
	.byte $00,$c5,$c1,$c0,$00,$03
@env19:
	.byte $00,$cf,$7f,$00,$02
@env20:
	.byte $00,$cf,$04,$c0,$00,$03
@env21:
	.byte $0c,$c6,$05,$c5,$0f,$c4,$13,$c3,$32,$c2,$00,$09,$c3,$13,$c2,$00,$0e
@env22:
	.byte $c0,$d3,$c0,$00,$02
@env23:
	.byte $07,$ca,$cb,$cb,$ca,$00,$04,$c9,$c6,$c6,$c5,$00,$0a
@env24:
	.byte $04,$c9,$00,$01,$c9,$c6,$00,$05
@env25:
	.byte $00,$c5,$c3,$c2,$03,$c1,$04,$c0,$00,$07
@env26:
	.byte $00,$ca,$c8,$c6,$c3,$c3,$c2,$02,$c1,$00,$08
@env27:
	.byte $c0,$7f,$00,$01
@env28:
	.byte $12,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c5,$00,$0f,$c4,$03,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$1a
@env29:
	.byte $07,$c7,$c9,$02,$c8,$00,$04,$c5,$c5,$c4,$c4,$00,$0a
@env30:
	.byte $07,$c8,$c9,$c9,$c8,$00,$04,$c7,$c5,$c5,$c4,$00,$0a
@env31:
	.byte $7f,$00,$00
@env32:
	.byte $c2,$7f,$00,$00
@env33:
	.byte $c1,$bb,$c0,$00,$02
@env34:
	.byte $c1,$08,$c0,$00,$02
@env35:
	.byte $c1,$7f,$00,$00
@env36:
	.byte $00,$c3,$10,$c2,$0f,$c1,$00,$05
@env37:
	.byte $bc,$c2,$c0,$00,$02
@env38:
	.byte $00,$cb,$c8,$c6,$c5,$c5,$c4,$03,$c3,$06,$c2,$03,$c1,$00,$0c
@env39:
	.byte $c2,$07,$c1,$00,$02
@env40:
	.byte $00,$cf,$ce,$cb,$c8,$c6,$c4,$c3,$c3,$c2,$00,$09
@env41:
	.byte $00,$c1,$c2,$c3,$c4,$c5,$c6,$00,$06
@env42:
	.byte $00,$c8,$7f,$00,$02
@env43:
	.byte $b4,$c0,$08,$cc,$03,$c0,$00,$05
@env44:
	.byte $c8,$7f,$00,$00
@env45:
	.byte $c0,$07,$c2,$00,$02
@env46:
	.byte $00,$c0,$1a,$c0,$c0,$c1,$c2,$02,$c1,$c0,$c0,$bf,$be,$02,$bf,$00,$03
@env47:
	.byte $c3,$c1,$c0,$00,$02
@env48:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$cc,$cc,$00,$00
@env49:
	.byte $cc,$c0,$c0,$cf,$c3,$c3,$d3,$c7,$c7,$d8,$cc,$cc,$db,$cf,$cf,$df,$d3,$d3,$e4,$d8,$d8,$df,$d3,$d3,$db,$cf,$cf,$d8,$cc,$cc,$d3,$c7,$c7,$cf,$c3,$c3,$00,$00
@env50:
	.byte $00,$ce,$7f,$00,$02
@env51:
	.byte $c2,$c1,$c0,$00,$02
@env52:
	.byte $00,$ca,$c7,$c4,$c3,$c3,$c2,$02,$c1,$00,$08
@env53:
	.byte $c1,$07,$c2,$00,$02
@env54:
	.byte $00,$cd,$ca,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$00,$09
@env55:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$4c,$40 ; 00 1 (Pitch:12)
	.byte $07+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$4c,$40 ; 01 2 (Pitch:12)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$4c,$40 ; 02 3 (Pitch:12)
	.byte $15+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$4c,$40 ; 03 4 (Pitch:12)
	.byte $1c+.lobyte(FAMISTUDIO_DPCM_PTR),$19,$4c,$40 ; 04 6 (Pitch:12)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $a2
@song0ref2:
	.byte $16, $8b, $45, $81, $43, $11, $8f, $9e, $1d, $8b, $45, $81, $43, $16, $8f, $a0, $19, $8b, $45, $81, $43, $1d, $8f, $a2
	.byte $11, $8b, $45, $81, $43, $19, $8f, $9e, $12, $8b, $45, $81, $43, $11, $8f, $a0, $1d, $8b, $45, $81, $43, $12, $8f, $9e
	.byte $12, $8b, $45, $81, $43, $1d, $8f, $48
	.byte $41, $2a
	.word @song0ref1
@song0ref61:
	.byte $48, $a0, $16, $8b, $45, $81, $43, $10, $8f, $9e, $1c, $8b, $45, $81, $43, $16, $8f, $a2, $19, $8b, $45, $81, $43, $1c
	.byte $8f, $a0, $10, $8b, $45, $81, $43, $19, $8f, $13, $8b, $45, $81, $43, $10, $8f, $9e, $1c, $8b, $45, $81, $43, $13, $8f
	.byte $a2, $13, $8b, $45, $81, $43, $1c, $8f
	.byte $41, $2a
	.word @song0ref61
	.byte $48
	.byte $41, $2a
	.word @song0ref2
	.byte $48
	.byte $41, $2a
	.word @song0ref1
	.byte $41, $2a
	.word @song0ref61
	.byte $41, $2a
	.word @song0ref61
	.byte $48
	.byte $41, $2a
	.word @song0ref2
	.byte $48
	.byte $41, $2a
	.word @song0ref1
	.byte $41, $2a
	.word @song0ref61
	.byte $41, $2a
	.word @song0ref61
	.byte $48, $c4
@song0ref150:
	.byte $16, $8d, $45, $43, $40, $0a, $8f, $1d, $8d, $45, $43, $40, $0a, $8f, $19, $8d, $45, $43, $40, $0a, $8f, $11, $8d, $45
	.byte $43, $40, $0a, $8f, $12, $8d, $45, $43, $40, $0a, $8f, $1d, $8d, $45, $43, $40, $0a, $8f, $12, $8d, $45, $43, $40, $0a
	.byte $8f, $48
	.byte $41, $23
	.word @song0ref150
@song0ref203:
	.byte $48, $16, $8d, $45, $43, $04, $8f, $1c, $8d, $45, $43, $04, $8f, $19, $8d, $45, $43, $04, $8f, $10, $8d, $45, $43, $04
	.byte $8f, $13, $8d, $45, $43, $04, $8f, $1c, $8d, $45, $43, $04, $8f, $13, $8d, $45, $43, $04, $8f, $48, $16, $8d, $45, $43
	.byte $04, $8f, $1c, $8d, $45, $43, $04, $8f, $19, $8d, $45, $43, $04, $8f, $10, $8d, $45, $43, $04, $8f, $13, $8d, $45, $43
	.byte $07, $8f, $1c, $8d, $45, $43, $04, $8f, $13, $8d, $45, $43, $04, $8f, $48
	.byte $41, $23
	.word @song0ref150
	.byte $48
	.byte $41, $23
	.word @song0ref150
	.byte $41, $46
	.word @song0ref203
	.byte $48
	.byte $41, $23
	.word @song0ref150
	.byte $48
	.byte $41, $23
	.word @song0ref150
	.byte $41, $46
	.word @song0ref203
	.byte $48
	.byte $41, $23
	.word @song0ref150
	.byte $48
	.byte $41, $23
	.word @song0ref150
	.byte $41, $37
	.word @song0ref203
	.byte $48, $13, $8f, $45, $43, $07, $8f, $48, $1c, $8f, $45, $43, $04, $91, $48, $13, $91, $45, $43, $04, $93, $48, $00, $81
	.byte $8e, $40, $0b, $fd, $43, $50, $b9, $0b, $14, $a9, $43, $08, $ff, $ef, $45, $eb, $00, $ff, $ad, $44, $00
@song0ch1:
	.byte $c0, $40, $0a, $ff, $f9, $ff, $fb, $43, $04, $ff, $f9, $ff, $fb, $8e
@song0ref382:
	.byte $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45
	.byte $8f, $91, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $a1, $40, $0a, $8f, $45, $8f, $40, $0a
	.byte $89, $45, $83, $40, $0a, $89, $45, $83, $04, $8f, $45, $a1, $04, $8f, $45, $a1, $04, $8f, $45, $a1, $04, $8f, $45, $a1
	.byte $04, $8f, $45, $8f, $91, $04, $8f, $45, $a1, $04, $8f, $45, $a1, $04, $8f, $07, $a1, $04, $c5
	.byte $41, $4d
	.word @song0ref382
	.byte $87, $45, $85, $07, $87, $45, $85, $04, $99, $45, $85, $04, $99, $45, $85, $4e, $06
	.byte $41, $4d
	.word @song0ref382
	.byte $87, $45, $85, $07, $87, $45, $85, $04, $99, $45, $85, $04, $99, $45, $85, $4e, $06
	.byte $41, $4d
	.word @song0ref382
	.byte $87, $45, $85, $07, $87, $45, $85, $04, $99, $45, $85, $04, $99, $45, $85, $4e, $06
	.byte $41, $4d
	.word @song0ref382
	.byte $87, $45, $85, $07, $87, $45, $85, $04, $99, $45, $85, $04, $99, $45, $85, $4e, $06
	.byte $41, $4d
	.word @song0ref382
	.byte $89, $45, $85, $07, $87, $45, $85, $04, $9d, $45, $85, $04, $9f, $45, $87, $40, $0b, $ff, $81, $43, $50, $b9, $0b, $14
	.byte $a9, $43, $08, $ff, $ff, $85, $45, $d5, $00, $ff, $ad, $44, $00
@song0ch2:
	.byte $8e, $0a, $ff, $f9, $43, $0a, $ff, $d5, $43, $50, $1c, $16, $14, $8f, $43, $50, $42, $14, $10, $8f, $43, $04, $ff, $f9
	.byte $43, $04, $ff, $f9, $0a, $ff, $f9, $43, $0a, $ff, $d5, $43, $50, $1c, $16, $14, $8f, $43, $50, $42, $14, $10, $8f, $43
	.byte $04, $ff, $f9, $43, $04, $ff, $f9, $0a, $ff, $f9, $43, $0a, $ff, $d5, $43, $50, $1c, $16, $14, $8f, $43, $50, $42, $14
	.byte $10, $8f, $43, $04, $ff, $f9, $43, $04, $ff, $f9, $b2, $2e, $ff, $b1, $31, $c5, $30, $ff, $b1, $2d, $c5, $31, $ff, $d5
	.byte $30, $8f, $2f, $8f, $2e, $ff, $f9, $2e, $ff, $b1, $31, $c5, $30, $ff, $b1, $2d, $c5, $2c, $c5, $34, $ff, $8d, $31, $8f
	.byte $33, $8f, $34, $ff, $f9, $31, $ff, $b1, $30, $c5, $31, $ff, $b1, $33, $c5, $34, $ff, $d5, $33, $8f, $34, $8f, $37, $ff
	.byte $d5, $39, $a1, $3a, $ff, $b1, $35, $c5, $31, $ff, $8d, $2e, $b3, $2d, $b3, $2c, $c5, $34, $ff, $8d, $31, $8f, $33, $8f
	.byte $34, $ff, $8d, $37, $9d, $00, $83, $37, $9f, $00, $83, $37, $a1, $00, $85, $37, $93, $38, $ff, $81, $43, $50, $0c, $44
	.byte $39, $93, $08, $ff, $ff, $85, $00, $ff, $ff, $85, $44, $00
@song0ch3:
	.byte $ff, $fb, $ff, $fb
@song0ref803:
	.byte $94, $34, $85, $00, $87, $80, $32, $85, $00, $99, $32, $87, $00, $85, $8c, $32, $85, $00, $99, $80, $32, $85, $00, $87
	.byte $8c, $32, $85, $00, $99, $80, $32, $87, $00, $85, $8c, $32, $85, $00, $99, $32, $85, $00, $87, $80, $32, $87, $00, $85
	.byte $41, $28
	.word @song0ref803
@song0ref854:
	.byte $94, $34, $85, $00, $87, $80, $32, $85, $00, $99, $32, $87, $00, $85, $8c, $32, $85, $80, $31, $87, $32, $87, $00, $85
	.byte $32, $85, $00, $87, $8c, $32, $85, $00, $99, $80, $32, $87, $00, $85, $8c, $32, $85, $00, $87, $80, $32, $87, $8c, $32
	.byte $85, $31, $83, $00, $83, $32, $83, $00, $83, $32, $83, $00, $83
	.byte $41, $34
	.word @song0ref854
	.byte $41, $34
	.word @song0ref854
	.byte $41, $1b
	.word @song0ref854
	.byte $87, $30, $85, $00, $87, $80, $31, $87, $00, $85, $32, $85, $00, $87, $8c, $31, $87, $00, $85, $80, $31, $85, $00, $87
	.byte $32, $87, $00, $85
	.byte $41, $34
	.word @song0ref854
	.byte $41, $34
	.word @song0ref854
	.byte $41, $34
	.word @song0ref854
	.byte $41, $20
	.word @song0ref854
	.byte $8c, $31, $85, $00, $81, $80, $32, $83, $00, $83, $32, $83, $00, $83, $8c, $31, $85, $00, $81, $80, $32, $83, $00, $83
@song0ref988:
	.byte $32, $83, $00, $83, $94, $34, $85, $00, $87, $80, $32, $85, $00, $87, $9a, $30, $8f, $80, $32, $87, $00, $85, $94, $2d
	.byte $8f, $80, $32, $87, $00, $85, $9a, $30, $8f, $30, $8f, $00, $8f, $80, $32, $87, $00, $85, $8c, $32, $85, $00, $87, $80
	.byte $32, $87, $32, $85, $94, $31, $89, $80, $32, $83, $9a, $30, $83, $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $2a
	.word @song0ref988
	.byte $94, $2e, $89, $80, $32, $83, $94, $2e, $83, $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $2a
	.word @song0ref988
	.byte $94, $2e, $89, $80, $32, $83, $94, $2e, $83, $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $2a
	.word @song0ref988
	.byte $94, $2e, $89, $80, $32, $83, $94, $2e, $83, $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $30
	.word @song0ref988
	.byte $80
	.byte $41, $1c
	.word @song0ref988
	.byte $94, $2c, $91, $80, $32, $87, $00, $85, $94, $2c, $91, $80, $32, $89, $32, $85, $94, $2c, $8b, $80, $32, $85, $94, $2e
	.byte $83, $80, $32, $85, $00, $85, $94, $2f, $a9, $43, $50, $fc, $3b, $34, $bf, $43, $50, $f2, $34, $21, $a9, $43, $50, $e5
	.byte $21, $0f, $93, $c2, $40, $0c, $ff, $99, $00, $ff, $ff, $f1, $44, $00
@song0ch4:
	.byte $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb
	.byte $52, $8e, $91, $52, $9c, $91, $52, $ac, $91, $52, $c2, $ff, $c5
@song0ref1236:
	.byte $ff, $fb, $ff
@song0ref1239:
	.byte $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff, $fb, $ff
	.byte $fb, $ff, $8f, $a5, $a7, $ab, $ff, $ff, $ff, $ff, $ff, $bf, $44, $00
@song0ch5:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch6:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch7:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch8:
	.byte $84
@song0ref1300:
	.byte $40, $0a, $ff, $f9, $ff, $d7, $43, $50, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $fb, $40, $0a, $ff, $f9, $ff
	.byte $d7, $43, $50, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $fb, $40, $0a, $ff, $f9, $ff, $d7, $43, $50, $ff, $0a
	.byte $04, $a1, $43, $40, $04, $ff, $f9, $ff, $fb
	.byte $41, $24
	.word @song0ref1300
	.byte $40, $0a, $ff, $f9, $ff, $d7, $43, $50, $ff, $0a, $04, $a1, $43, $40, $04, $ff, $f9, $ff, $8f, $a5, $a7, $ab, $40, $07
	.byte $93, $43, $40, $08, $ff, $ff, $dd, $5c, $ff, $ff, $9b, $00, $a9, $44, $00
@song0ch9:
	.byte $94, $40, $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $40, $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $40
	.byte $01, $ff, $f9, $ff, $fb, $00, $ff, $f9, $ff, $fb, $96
@song0ref1435:
	.byte $0a, $ff, $f9, $ff, $d7, $43, $50, $ff, $16, $14, $8f, $43, $50, $fe, $14, $10, $8f, $43, $04, $ff, $f9, $ff, $f5, $5c
	.byte $83, $0a, $ff, $f9, $ff, $d7, $43, $50, $ff, $16, $14, $8f, $43, $50, $fe, $14, $10, $8f, $43, $04, $ff, $f9, $ff, $f5
	.byte $5c, $83
	.byte $41, $1d
	.word @song0ref1435
	.byte $8f, $a5, $a7, $a1, $5c, $83, $00, $81, $ff, $ff, $ff, $ff, $ff, $bf, $44, $00
@song0ch10:
@song0ref1505:
	.byte $88, $40, $01, $ff, $f9, $ff, $fb, $80, $10, $97, $5c, $99, $10, $97, $5c, $99, $10, $97, $5c, $99, $10, $97, $5c, $99
	.byte $10, $97, $5c, $87, $91, $10, $97, $5c, $99, $10, $97, $5c, $99, $10, $8f, $10, $8f, $5c, $8f, $10, $8f, $5c, $8f, $10
	.byte $8f, $5c, $8f
	.byte $41, $30
	.word @song0ref1505
	.byte $41, $30
	.word @song0ref1505
	.byte $92
	.byte $41, $20
	.word @song0ref1435
	.byte $41, $1d
	.word @song0ref1435
	.byte $8f, $a5, $a7, $a1, $5c, $83, $00, $81, $8e, $08, $ff, $ff, $ff, $b5, $5c, $ff, $d9, $00, $a9, $44, $00
@song0ch11:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch12:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch13:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch14:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch15:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch16:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch17:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch18:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song0ch19:
	.byte $41, $1d
	.word @song0ref1236
	.byte $41, $25
	.word @song0ref1239
@song1ch0:
	.byte $ff, $c3, $48, $ff, $c3, $48, $8e
@song1ref8:
	.byte $07, $83, $00, $85, $07, $83, $00, $85, $07, $8b, $00, $8b, $07, $8b, $00, $8b, $07, $83, $00, $85, $07, $83, $00, $85
	.byte $07, $8b, $00, $8b, $07, $83, $00, $85, $07, $83, $00, $85, $07, $8b, $00, $8b, $48, $08, $83, $00, $85, $08, $83, $00
	.byte $85, $08, $8b, $00, $8b, $08, $8b, $00, $8b, $08, $83, $00, $85, $08, $83, $00, $85, $06, $83, $00, $85, $06, $83, $00
	.byte $85, $06, $8b, $00, $8b, $06, $83, $00, $85, $06, $83, $00, $85, $48, $ff, $c3, $48, $ff, $c3, $48
	.byte $41, $53
	.word @song1ref8
	.byte $d9
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8d
@song1ref109:
	.byte $9c, $18, $8b, $8e, $40, $0c, $8b, $40, $0c, $8b, $9c, $18, $8b, $8e, $40, $0c, $8b, $40, $0c, $85, $00, $83, $40, $0c
	.byte $83, $00, $85, $9c, $18, $85, $00, $83, $18, $83, $00, $85, $18, $91, $8e, $0c, $85, $9c, $18, $91, $8e, $40, $0c, $85
	.byte $48, $01, $8b, $9c, $19, $8b, $8e, $01, $8b, $01, $8b, $9c, $19, $8b, $8e, $01, $8b, $01, $85, $00, $83, $01, $83, $00
	.byte $85, $40, $0a, $8b, $9c, $16, $99, $22, $a7, $48, $a6, $1f, $a7, $8e, $40, $0c, $8b, $a6, $1f, $8b, $8e, $40, $0c, $8b
	.byte $0c, $85, $00, $83, $18, $83, $00, $85, $18, $85, $00, $83, $0c, $83, $00, $85, $a6, $1f, $99, $1f, $99, $48, $20, $99
	.byte $8e, $01, $8b
@song1ref232:
	.byte $9c, $25, $99, $8e, $19, $8b, $1c, $8b, $0a, $8b, $00, $8b, $0a, $8b, $16, $8b, $19, $8b, $1d, $8b, $22, $8b, $48, $1f
	.byte $8b
	.byte $41, $4c
	.word @song1ref109
	.byte $24, $85, $00, $83, $24, $83, $00, $85, $a6, $1f, $99, $1f, $99, $48, $20, $99, $8e, $01, $8b, $9c, $25, $99, $86, $19
	.byte $8b, $1c, $8b, $0a, $8b, $00, $8b, $8e, $0a, $8b, $86, $16, $8b, $88, $19, $8b, $1d, $8b, $84, $22, $8b, $48, $24, $8b
	.byte $9c, $24, $8b, $84, $1f, $8b, $1e, $8b, $1f, $8b, $18, $8b, $1b, $8b, $18, $8b, $13, $8b, $0c, $8b, $1b, $99, $1a, $99
@song1ref332:
	.byte $48, $19, $8b, $86, $14, $8b, $84, $19, $85, $00, $83, $19, $83, $00, $85, $86, $14, $8b, $84, $18, $8b, $19, $8b, $86
	.byte $0d, $8b, $84, $18, $8b, $19, $8b, $86, $16, $8b, $84, $18, $8b, $86, $24, $85, $00, $83, $24, $81, $00, $24, $81, $00
	.byte $81, $48, $8d, $88, $24, $83, $00, $85, $86, $24, $8b, $24, $83, $00, $85, $88, $18, $99, $17, $8b, $18, $8b, $0c, $8b
	.byte $0c, $83, $00, $85, $0c, $85, $00, $83, $18, $83, $00, $85, $18, $85, $00, $83, $18, $8b, $48, $a6, $1f, $85, $43, $20
	.byte $9f
	.byte $41, $14
	.word @song1ref232
	.byte $48, $84, $1f, $8b, $9c, $24, $8b, $84, $24, $8b, $1b, $8b, $1f, $8b, $20, $8b, $18, $8b, $13, $8b, $1a, $85, $00, $83
	.byte $1b, $85, $00, $83, $1b, $99, $1b, $8b, $1a, $8b
	.byte $41, $4c
	.word @song1ref332
	.byte $48, $a6, $20, $a7
	.byte $41, $14
	.word @song1ref232
	.byte $48, $00, $ff, $c1, $48, $ff, $c3, $48
	.byte $41, $40
	.word @song1ref8
	.byte $05, $83, $00, $85, $05, $83, $00, $85, $05, $8b, $00, $8b, $05, $83, $00, $85, $05, $83, $00, $85, $48, $b0, $28, $85
	.byte $29, $c9, $45, $99, $24, $8b, $22, $8b, $45, $85, $00, $83, $24, $8b, $45, $85, $00, $83, $22, $8b, $48, $00, $8b, $25
	.byte $b5, $00, $8b, $25, $8b, $24, $8b, $22, $a7, $1a, $a7, $48, $1b
@song1ref548:
	.byte $df, $00, $99, $1b, $83, $00, $85, $1b, $8b, $00, $8b, $27, $85, $00, $83, $27, $83, $00, $85, $48, $25, $a7, $20, $a7
	.byte $22, $a7, $25, $a7, $22, $99, $48, $23, $85, $24, $c9, $45, $99, $1f, $8b, $20, $8b, $45, $85, $00, $83, $24, $8b, $45
	.byte $85, $00, $83, $20, $8b, $48, $22, $a7, $25, $a7, $22, $99, $16, $8b, $19, $8b, $00, $8b, $25, $8b, $00, $8b, $22, $8b
	.byte $48, $24
	.byte $41, $18
	.word @song1ref548
	.byte $99, $16, $8b, $18, $8b, $22, $85, $00, $83, $16, $8b, $18, $8b, $22, $83, $00, $85, $42
	.word @song1ch0loop
@song1ch1:
	.byte $4e, $ff, $8e
@song1ref648:
	.byte $40, $0c, $83, $00, $85, $40, $0c, $83, $00, $85, $40, $0c, $8b, $00, $8b, $40, $0c, $8b, $00, $8b, $40, $0c, $83, $00
	.byte $85, $40, $0c, $83, $00, $85, $40, $0c, $8b, $00, $8b, $40, $0c, $83, $00, $85, $40, $0c, $83, $00, $85, $40, $0c, $8b
	.byte $00, $8b, $01, $83, $00, $85, $01, $83, $00, $85, $01, $8b, $00, $8b, $01, $8b, $00, $8b, $01, $83, $00, $85, $01, $83
	.byte $00, $85, $40, $0b, $83, $00, $85, $40, $0b, $83, $00, $85, $40, $0b, $8b, $00, $8b, $40, $0b, $83, $00, $85, $40, $0b
	.byte $83, $00, $85, $4e, $ff
	.byte $41, $54
	.word @song1ref648
	.byte $4e, $ff
	.byte $41, $54
	.word @song1ref648
	.byte $4e, $ff
	.byte $41, $53
	.word @song1ref648
	.byte $d9
@song1ch1loop:
@song1ref764:
	.byte $88, $40, $0c, $8b, $84, $0c, $8b, $40, $0c, $8b, $86, $40, $0c, $8b, $84, $0c, $8b, $88, $40, $0c, $8b, $40, $0c, $85
	.byte $00, $83, $84, $40, $0c, $83, $00, $85, $40, $0c, $8b, $86, $40, $0c, $8b, $0c, $85, $00, $83, $88, $0c, $83, $00, $85
	.byte $40, $0c, $8b, $86, $40, $0c, $8b, $88, $01, $8b, $0d, $8b, $01, $8b, $84, $01, $8b, $0d, $8b, $01, $8b, $88, $01, $85
	.byte $00, $83, $84, $01, $83, $00, $85, $40, $0a, $8b, $86, $40, $0a, $8b, $0a, $85, $00, $83, $0a, $83, $00, $85, $84, $40
	.byte $0a, $8b, $86, $40, $0a, $8b
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $41, $48
	.word @song1ref764
	.byte $42
	.word @song1ch1loop
@song1ch2:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $a7, $ae, $50, $80, $0c, $18, $99, $0c, $ff, $c1, $0d, $ed, $0b, $d1, $40, $0c, $b5
	.byte $0c, $ff, $89, $0d, $ed, $0b, $99, $17, $8b, $00, $8b, $23, $8b, $23, $8b, $00, $8b, $b6, $30, $83, $30, $85, $30, $8b
	.byte $30, $8b, $2b, $8b, $26, $8b
@song1ch2loop:
@song1ref963:
	.byte $50, $33, $24, $1a, $99, $00, $99, $2a, $85, $00, $ad, $50, $66, $24, $1a, $8b, $2a, $85, $00, $83, $50, $66, $24, $1a
	.byte $8b, $00, $8b, $2a, $83, $00, $93
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
@song1ref1000:
	.byte $50, $66, $24, $1a, $8b, $00, $a7, $2a, $85, $00, $91, $2a, $85, $00, $83, $50, $66, $24, $1a, $8b, $50, $66, $24, $1a
	.byte $8b, $2a, $85, $00, $83, $50, $66, $24, $1a, $8b, $50, $66, $24, $1a, $8b, $2a, $85, $00, $83, $2a, $85, $00, $83
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $16
	.word @song1ref963
	.byte $41, $20
	.word @song1ref1000
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ref1122:
	.byte $8c, $34, $85, $00, $83, $80, $31, $8b, $31, $8b, $31, $83, $31, $85, $96, $2d, $8b, $80, $31, $83, $00, $85, $31, $85
	.byte $00, $83, $96, $31, $8b, $8c, $34, $85, $00, $83, $96, $2d, $8b, $8c, $34, $85, $00, $83, $80, $31, $83, $31, $85, $96
	.byte $2d, $8b, $2d, $8b
	.byte $41, $2a
	.word @song1ref1122
	.byte $41, $2a
	.word @song1ref1122
	.byte $41, $2a
	.word @song1ref1122
@song1ref1183:
	.byte $82, $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $83, $31, $85, $92, $31, $8b, $80, $31, $83, $00, $85, $31, $85
	.byte $00, $83, $96, $31, $8b, $82, $34, $8b, $92, $31, $8b, $82, $34, $8b, $80, $31, $83, $31, $85, $92, $31, $8b, $80, $31
	.byte $83, $31, $85
	.byte $41, $26
	.word @song1ref1183
	.byte $41, $26
	.word @song1ref1183
	.byte $41, $26
	.word @song1ref1183
	.byte $00, $8b, $92, $31, $85, $31, $83, $31, $8b, $31, $8b, $31, $8b, $31, $8b
@song1ch3loop:
@song1ref1259:
	.byte $82, $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $83, $31, $85, $8a, $2f, $99, $80, $31, $85, $00, $83, $96, $31
	.byte $8b, $82, $34, $8b, $8a, $2f, $8b, $82, $34, $8b, $80, $31, $83, $31, $85, $8a, $2f, $8b, $80, $31, $83, $31, $85
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
@song1ref1312:
	.byte $82, $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $83, $31, $85, $8a, $2f, $8b, $80, $31, $83, $00, $85, $8a, $2f
	.byte $8b, $82, $34, $8b, $34, $8b, $8a, $2f, $8b, $82, $34, $8b, $34, $8b, $8a, $2f, $8b, $2f, $8b
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $22
	.word @song1ref1259
	.byte $41, $20
	.word @song1ref1312
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ref1430:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $ff, $97
@song1ch4loop:
@song1ref1448:
	.byte $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3, $ff, $c3
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch4loop
@song1ch5:
	.byte $41, $11
	.word @song1ref1430
@song1ch5loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch5loop
@song1ch6:
	.byte $41, $11
	.word @song1ref1430
@song1ch6loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch6loop
@song1ch7:
	.byte $41, $11
	.word @song1ref1430
@song1ch7loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch7loop
@song1ch8:
	.byte $41, $11
	.word @song1ref1430
@song1ch8loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch8loop
@song1ch9:
	.byte $41, $11
	.word @song1ref1430
@song1ch9loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch9loop
@song1ch10:
	.byte $41, $11
	.word @song1ref1430
@song1ch10loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch10loop
@song1ch11:
	.byte $41, $11
	.word @song1ref1430
@song1ch11loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch11loop
@song1ch12:
	.byte $41, $11
	.word @song1ref1430
@song1ch12loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch12loop
@song1ch13:
	.byte $41, $11
	.word @song1ref1430
@song1ch13loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch13loop
@song1ch14:
	.byte $41, $11
	.word @song1ref1430
@song1ch14loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch14loop
@song1ch15:
	.byte $41, $11
	.word @song1ref1430
@song1ch15loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch15loop
@song1ch16:
	.byte $41, $11
	.word @song1ref1430
@song1ch16loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch16loop
@song1ch17:
	.byte $41, $11
	.word @song1ref1430
@song1ch17loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch17loop
@song1ch18:
	.byte $41, $11
	.word @song1ref1430
@song1ch18loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch18loop
@song1ch19:
	.byte $41, $11
	.word @song1ref1430
@song1ch19loop:
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $41, $12
	.word @song1ref1448
	.byte $ff, $c3, $42
	.word @song1ch19loop
@song2ch0:
	.byte $9b, $9c, $24, $b5, $45, $b5, $00, $b5, $48, $ff, $c1, $48, $9b, $a6, $1f, $a5, $9c, $24, $b3, $45, $a5, $00, $99, $48
	.byte $a6, $20, $a5, $9c, $25, $a5, $a6, $21, $a5, $9c, $26, $a5, $27, $99, $48, $8d, $26, $9f, $45, $81, $43, $26, $85, $43
	.byte $25, $83, $43, $24, $83, $43, $23, $83, $00, $e5, $48, $ff, $b3, $48, $ff, $af, $48, $ff, $ab
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8b
@song2ref73:
	.byte $9c, $1a, $89, $8e, $02, $89, $02, $89, $9c, $1a, $89, $8e, $02, $89, $02, $83, $00, $83, $02, $81, $00, $85, $9c, $1a
	.byte $83, $00, $83, $1a, $83, $00, $83
@song2ref104:
	.byte $1a, $8d, $8e, $0e, $85, $9c, $1a, $8d, $8e, $02, $85, $48, $03, $89, $9c, $1b, $89, $8e, $03, $89, $03, $89, $9c, $1b
	.byte $89, $8e, $03, $89, $03, $83, $00, $83, $03, $81, $00, $85, $9c, $1b, $a1, $27, $a1, $48, $a6, $21, $a1, $8e, $02, $89
	.byte $a6, $21, $89, $8e, $02, $89, $0e, $83, $00, $83, $1a, $81, $00, $85, $1a, $83, $00, $83, $0e
@song2ref171:
	.byte $81, $00, $85, $a6, $21, $95, $21, $95, $48, $22, $95, $8e, $03, $89, $9c, $27, $95, $8e, $1b, $89, $1e, $89, $0f, $89
	.byte $12, $89, $1a, $89, $1b, $89, $1e, $89, $22, $89, $1e, $89, $48, $21, $89
	.byte $41, $17
	.word @song2ref73
	.byte $81, $00, $85
	.byte $41, $1c
	.word @song2ref104
	.byte $ba, $24, $a1, $be, $20, $a1, $48, $bc, $21, $95, $45, $89, $21, $93, $45, $8e, $02, $89, $0e, $83, $00, $83, $1a, $81
	.byte $00, $85, $26, $83, $00, $83, $26
	.byte $41, $13
	.word @song2ref171
	.byte $22, $89, $1e, $89, $1b, $89, $27, $89, $22, $89, $1e, $89, $2a, $89, $27, $89, $22, $89
@song2ref271:
	.byte $48, $1a, $89, $1d, $89, $21, $83, $00, $83, $1a, $83, $00, $83, $1d, $89, $21, $89, $1a, $83, $00, $83, $1d, $83, $00
	.byte $83, $21, $89, $1a, $89, $1d, $83, $00, $83, $21, $83, $00, $83, $1a, $89, $1d, $83, $00, $83, $48, $1b, $89, $1e, $89
	.byte $22
@song2ref320:
	.byte $83, $00, $83, $1b, $83, $00, $83, $1e, $89, $22, $89, $1b, $83, $00, $83, $1e, $83, $00, $83, $22, $89, $1b, $89, $1e
	.byte $83, $00, $83, $22, $83, $00, $83, $1b, $89, $1e, $83, $00, $83
	.byte $41, $54
	.word @song2ref271
	.byte $48, $b0, $21, $ff, $8d, $22, $95, $48, $1d, $89, $43, $1e, $b9, $43, $1d, $85, $43, $1c, $85, $43, $19, $85, $43, $16
	.byte $85, $00, $8d, $22, $89, $24, $89, $2e, $89, $30, $89, $48, $2c, $89, $43, $2d, $b9, $43, $2c, $85, $00, $81, $2d, $95
	.byte $00, $89, $43, $2d, $81, $00, $85, $2d, $87, $00, $2d, $81, $00, $85, $2d, $81, $00, $85, $48, $8e, $27, $89, $2a, $89
	.byte $2e
	.byte $41, $20
	.word @song2ref320
	.byte $83, $00, $83, $1b, $83, $00, $83
	.byte $41, $54
	.word @song2ref271
	.byte $41, $54
	.word @song2ref271
	.byte $42
	.word @song2ch0loop
@song2ch1:
	.byte $88, $40, $0c, $8b, $84, $0c, $8b, $40, $0c, $8b, $86, $40, $0c, $8b, $84, $0c, $8b, $88, $40, $0c, $8b, $40, $0c, $85
	.byte $00, $83, $84, $40, $0c, $83, $00, $85, $40, $0c, $8b, $86, $40, $0c, $8b, $0c, $85, $00, $83, $88, $0c, $83, $00, $85
	.byte $40, $0c, $8b, $86, $40, $0c, $8b, $88, $01, $8b, $0d, $8b, $01, $8b, $84, $01, $8b, $0d, $8b, $01, $8b, $88, $01, $85
	.byte $00, $83, $84, $01, $81, $00, $85, $40, $0a, $8b, $86, $40, $0a, $8b, $0a, $85, $00, $83, $0a, $81, $00, $87, $84, $40
	.byte $0a, $8b, $86, $40, $0a, $8b, $88, $40, $0c, $8b, $84, $0c, $8b, $40, $0c, $8b, $86, $40, $0c, $89, $84, $0c, $8b, $88
	.byte $40, $0c, $8b, $40, $0c, $85, $00, $83, $84, $40, $0c, $81, $00, $85, $40, $0c, $8b, $86, $40, $0c, $8b, $0c, $85, $00
	.byte $83, $88, $0c, $81, $00, $85, $40, $0c, $8b, $86, $40, $0c, $8b, $88, $01, $8b, $0d, $8b, $01, $89, $84, $01, $8b, $0d
	.byte $8b, $01, $89, $88, $02, $8b, $0e, $8b, $02, $89, $84, $02, $8b, $0e, $8b, $02, $89, $03, $8b, $86, $0f, $8b, $88, $02
	.byte $8b, $84, $0e, $89, $02, $8b, $86, $02, $89, $84, $0e, $8b, $88, $02, $89, $02, $85, $00, $83, $84, $02, $81, $00, $85
	.byte $02, $8b, $86, $02, $89, $0e, $85, $00, $83, $88, $0e, $81, $00, $85, $02, $8b, $86, $02, $89, $88, $03, $8b, $0f, $89
	.byte $03, $8b, $84, $03, $89, $0f, $8b, $03, $89, $88, $03, $83, $00, $83, $84, $03, $81, $00, $85, $40, $0c, $8b, $86, $40
	.byte $0c, $89, $0c, $85, $00, $83, $0c, $81, $00, $85, $84, $40, $0c, $8b, $86, $40, $0c, $89, $88, $02, $8b, $84, $0e, $89
	.byte $02, $89, $86, $02, $89, $84, $0e, $8b, $88, $02, $89, $02, $83, $00, $83, $84, $02, $81, $00, $85, $02, $8b, $86, $02
	.byte $89, $0e, $83, $00, $83, $88, $0e, $81, $00, $85, $02, $8b, $86, $02, $89, $88, $03, $8b
@song2ref782:
	.byte $0f, $89, $03, $89, $84, $03, $89, $0f, $89, $03, $89, $88, $03, $83, $00, $83, $84, $03, $81, $00, $85, $40, $0c, $8b
	.byte $86, $40, $0c, $89, $0c, $83, $00, $83, $0c, $81, $00, $85, $84, $40, $0c, $89, $86, $40, $0c, $89
@song2ch1loop:
@song2ref827:
	.byte $88
@song2ref828:
	.byte $02, $89, $84, $02, $89, $02, $89, $86, $02, $89, $84, $02, $89, $88, $02, $89, $02, $83, $00, $83, $84, $02, $81, $00
	.byte $85, $02, $89, $86, $02, $89, $02, $83, $00, $83, $88, $02, $81, $00, $85, $02, $89, $86, $02, $89, $88, $03, $89, $0f
	.byte $89, $03, $89, $84, $03, $89, $1b, $89, $03, $89, $88, $03, $83, $00, $83, $84, $03, $81, $00, $85, $86, $22, $83, $00
	.byte $83, $88, $24, $83, $00, $83, $84, $16, $89, $86, $18, $89, $88, $0a, $89, $86, $0c, $89, $88, $02, $89, $84, $0e, $89
	.byte $02, $89, $86, $02, $89, $84, $0e, $89, $88, $02, $89, $02, $83, $00, $83, $84, $02, $81, $00, $85, $02, $89, $86, $02
	.byte $89, $0e, $83, $00, $83, $88, $0e, $83, $00, $83, $02, $89, $86, $02, $89, $88, $03, $89
	.byte $41, $12
	.word @song2ref782
@song2ref969:
	.byte $03, $89, $86, $03, $89, $0f, $83, $00, $83, $0f, $81, $00, $85, $84, $03, $89, $86, $03, $89
	.byte $41, $6e
	.word @song2ref827
	.byte $41, $12
	.word @song2ref782
	.byte $41, $10
	.word @song2ref969
	.byte $88, $0f, $83, $00, $83, $0f, $83, $00, $83, $0f, $83, $00, $83
	.byte $41, $6e
	.word @song2ref828
	.byte $41, $12
	.word @song2ref782
	.byte $41, $10
	.word @song2ref969
	.byte $41, $6e
	.word @song2ref827
	.byte $41, $12
	.word @song2ref782
	.byte $41, $10
	.word @song2ref969
	.byte $41, $6e
	.word @song2ref827
	.byte $41, $12
	.word @song2ref782
	.byte $41, $10
	.word @song2ref969
	.byte $42
	.word @song2ch1loop
@song2ch2:
	.byte $b6, $50, $66, $24, $1a, $8b, $00, $a7, $2a, $85, $00, $ad, $50, $66, $24, $1a, $8b, $2a, $85, $00, $83, $50, $66, $24
	.byte $1a, $8b, $00, $8b, $2a, $85, $00, $91, $50, $76, $24, $1a, $8b, $00, $a7, $2a, $85, $00, $ab, $50, $76, $24, $1a, $8b
	.byte $2a, $85, $00, $83, $50, $76, $24, $1a, $8b, $00, $8b, $2a, $85, $00, $91, $50, $76, $24, $1a, $8b, $00, $a5, $2a, $85
	.byte $00, $ab, $50, $76, $24, $1a, $8b, $2a, $85, $00, $83, $50, $76, $24, $1a, $8b, $00, $89, $2a, $85, $00, $91, $50, $76
	.byte $24, $1a, $8b, $00, $a5, $2a, $85, $00, $8f, $2a, $85, $00, $83, $50, $76, $24, $1a, $8b, $50, $76, $24, $1a, $89, $2a
	.byte $85, $00, $83, $50, $76, $24, $1a, $8b, $50, $76, $24, $1a, $89, $2a, $85, $00, $83, $2a, $85, $00, $83, $50, $76, $24
	.byte $1a, $8b, $00, $a3, $2a, $85, $00, $a9
@song2ref1192:
	.byte $50, $76, $24, $1a, $8b, $2a, $83, $00, $83, $50, $76, $24, $1a, $8b, $00, $89, $2a, $85, $00, $8f, $50, $76, $24, $1a
	.byte $8b, $00, $a3, $2a, $85, $00, $a7
	.byte $41, $11
	.word @song2ref1192
	.byte $a1, $2a, $85, $00, $a7, $50, $76, $24, $1a, $8b, $2a, $83, $00, $83, $50, $76, $24, $1a, $89, $00, $89, $2a, $85, $00
	.byte $8f, $50, $76, $24, $1a, $8b, $00, $a1, $2a, $83, $00, $8f, $2a, $83, $00, $83, $50, $76, $24, $1a, $89, $50, $76, $24
	.byte $1a, $8b, $2a, $83, $00, $83, $50, $76, $24, $1a, $89, $50, $76, $24, $1a, $89, $2a, $83, $00, $83, $2a, $83, $00, $83
@song2ch2loop:
@song2ref1299:
	.byte $50, $76, $24, $1a, $89, $00, $95, $2a, $83, $00, $9b, $50, $76, $24, $1a, $89, $00, $89, $2a, $83, $00, $8f, $50, $76
	.byte $24, $1a, $89, $00, $89, $2a, $83, $00, $83, $2a, $83, $00, $83
	.byte $41, $1c
	.word @song2ref1299
	.byte $41, $1c
	.word @song2ref1299
@song2ref1342:
	.byte $50, $76, $24, $1a, $89, $00, $a1, $2a, $83, $00, $8f, $2a, $83, $00, $83, $50, $76, $24, $1a, $89, $50, $76, $24, $1a
	.byte $89, $30, $83, $30, $83, $30, $83, $00, $83, $30, $83, $00, $83, $2c, $83, $00, $83, $28, $83, $00, $83
	.byte $41, $1c
	.word @song2ref1299
	.byte $41, $1c
	.word @song2ref1299
	.byte $41, $1c
	.word @song2ref1299
	.byte $41, $24
	.word @song2ref1342
	.byte $30, $83, $00, $83, $30, $83, $00, $83, $28, $83, $00, $83
@song2ref1411:
	.byte $50, $76, $24, $1a, $89, $00, $a1, $2a, $83, $00, $a7, $50, $76, $24, $1a, $89, $2a, $83, $00, $83, $50, $76, $24, $1a
	.byte $89, $00, $89, $2a, $83, $00, $8f
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $16
	.word @song2ref1411
	.byte $41, $24
	.word @song2ref1342
	.byte $42
	.word @song2ch2loop
@song2ch3:
	.byte $82, $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $83, $31, $85, $8a, $2f, $99, $80, $31, $85, $00, $83, $96, $31
	.byte $8b, $82, $34, $8b, $8a, $2f, $8b, $82, $34, $8b, $80, $31, $83, $31, $85, $8a, $2f, $8b, $80, $31, $83, $31, $85, $82
	.byte $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $81, $31, $87
@song2ref1539:
	.byte $8a, $2f, $99, $80, $31, $85, $00, $83, $96, $31, $89, $82, $34, $8b, $8a, $2f, $8b, $82, $34, $8b, $80, $31, $81, $31
	.byte $87, $8a, $2f, $8b, $80, $31, $81, $31, $87, $82, $34, $8b, $80, $31, $8b, $98, $32, $8b, $80, $31, $81, $31, $85
	.byte $41, $11
	.word @song2ref1539
	.byte $85, $8a, $2f, $8b, $80, $31, $81, $31, $87, $82, $34, $8b, $80, $31, $8b, $98, $32, $89, $80, $31, $81, $31, $87, $8a
	.byte $2f, $8b, $80, $31, $81, $00, $85, $8a, $2f, $8b, $82, $34, $8b, $34, $89, $8a, $2f, $8b, $82, $34, $8b, $34, $89, $8a
	.byte $2f, $8b, $2f, $8b, $82, $34, $8b, $80, $31, $89, $98, $32, $8b, $80, $31, $81, $31, $85, $8a, $2f, $97, $80, $31, $85
@song2ref1661:
	.byte $00, $83, $96, $31, $89, $82, $34, $8b, $8a, $2f, $89, $82, $34, $8b, $80, $31, $81, $31, $85, $8a, $2f, $8b, $80, $31
	.byte $81, $31, $85, $82, $34, $8b, $80, $31, $89, $98, $32, $8b, $80, $31, $81, $31, $85, $8a, $2f, $97, $80, $31, $83
	.byte $41, $19
	.word @song2ref1661
	.byte $89, $80, $31, $81, $31, $85, $8a, $2f, $97, $80, $31, $83, $00, $83, $96, $31, $89, $82, $34, $8b, $8a, $2f, $89, $82
	.byte $34, $89, $80, $31, $81, $31, $85, $8a, $2f, $8b, $80, $31, $81, $31, $85, $82, $34, $8b
@song2ref1753:
	.byte $80, $31, $89, $98, $32, $89, $80, $31, $81, $31, $85, $8a, $2f, $89, $80, $31, $81, $00, $85, $8a, $2f, $89, $82, $34
	.byte $89, $34, $8b, $8a, $2f, $89, $82, $34, $89, $34, $89, $8a, $2f, $89, $2f, $89
@song2ch3loop:
@song2ref1794:
	.byte $82, $34, $89, $8c, $32, $83, $00, $83, $32, $83, $00, $83, $8a, $2f, $89, $8c, $32, $83, $00, $83, $32, $83, $00, $83
@song2ref1818:
	.byte $82, $34, $89, $8c, $32, $83, $00, $83, $8a, $2f, $89, $8c, $32, $83, $96, $31, $83, $82, $34, $89, $8c, $32, $83, $80
	.byte $31, $83, $8a, $2f, $89, $8c, $32, $83, $00, $83
	.byte $41, $2c
	.word @song2ref1794
	.byte $41, $2c
	.word @song2ref1794
	.byte $82, $34, $89
	.byte $41, $13
	.word @song2ref1753
	.byte $89, $8a, $2f, $89, $82, $34, $89, $34, $89, $8a, $2f, $89, $2f, $89
	.byte $41, $2c
	.word @song2ref1794
	.byte $41, $2c
	.word @song2ref1794
	.byte $41, $2c
	.word @song2ref1794
	.byte $82, $34, $89
	.byte $41, $13
	.word @song2ref1753
	.byte $89, $8a, $2f, $89, $82, $34, $89, $34, $89, $8a, $2f, $89, $2f, $89, $2f, $89, $2f, $89, $82, $34, $89
@song2ref1914:
	.byte $34, $89, $80, $31, $89, $98, $32, $89, $80, $31, $81, $31, $85, $8a, $2f, $95, $80, $31, $83, $00, $83, $96, $31, $89
	.byte $82, $34, $89, $8a, $2f, $89, $82, $34, $89, $80, $31, $81, $31, $85, $8a, $2f, $89, $80, $31, $81, $31, $85, $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82
	.byte $41, $22
	.word @song2ref1914
	.byte $82, $34, $89, $80, $31, $89, $98, $32, $89, $80, $31, $81, $31, $85, $8a, $2f, $95
	.byte $41, $18
	.word @song2ref1818
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ref2023:
	.byte $ff, $c3, $ff, $c1, $ff, $bd, $ff, $bb, $ff, $b5, $ff, $b3, $ff, $af, $ff, $ab
@song2ch4loop:
@song2ref2040:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $cb, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $42
	.word @song2ch4loop
@song2ch5:
	.byte $41, $10
	.word @song2ref2023
@song2ch5loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch5loop
@song2ch6:
	.byte $41, $10
	.word @song2ref2023
@song2ch6loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch6loop
@song2ch7:
	.byte $41, $10
	.word @song2ref2023
@song2ch7loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch7loop
@song2ch8:
	.byte $41, $10
	.word @song2ref2023
@song2ch8loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch8loop
@song2ch9:
	.byte $41, $10
	.word @song2ref2023
@song2ch9loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch9loop
@song2ch10:
	.byte $41, $10
	.word @song2ref2023
@song2ch10loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch10loop
@song2ch11:
	.byte $41, $10
	.word @song2ref2023
@song2ch11loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch11loop
@song2ch12:
	.byte $41, $10
	.word @song2ref2023
@song2ch12loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch12loop
@song2ch13:
	.byte $41, $10
	.word @song2ref2023
@song2ch13loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch13loop
@song2ch14:
	.byte $41, $10
	.word @song2ref2023
@song2ch14loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch14loop
@song2ch15:
	.byte $41, $10
	.word @song2ref2023
@song2ch15loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch15loop
@song2ch16:
	.byte $41, $10
	.word @song2ref2023
@song2ch16loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch16loop
@song2ch17:
	.byte $41, $10
	.word @song2ref2023
@song2ch17loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch17loop
@song2ch18:
	.byte $41, $10
	.word @song2ref2023
@song2ch18loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch18loop
@song2ch19:
	.byte $41, $10
	.word @song2ref2023
@song2ch19loop:
	.byte $41, $28
	.word @song2ref2040
	.byte $42
	.word @song2ch19loop
@song3ch0:
	.byte $a4
@song3ref2:
	.byte $14, $85, $45, $00, $43, $08, $87, $00, $1b, $85, $45, $00, $43, $08, $87, $00, $17, $85, $45, $00, $43, $08, $87, $00
	.byte $14, $85, $45, $00, $43, $08, $87, $00, $16, $85, $45, $00, $43, $08, $87, $00, $17, $85, $45, $00, $43, $08, $87, $00
	.byte $13, $85, $45, $00, $43, $07, $87, $00, $48
	.byte $41, $31
	.word @song3ref2
	.byte $48
	.byte $41, $31
	.word @song3ref2
	.byte $48
	.byte $41, $31
	.word @song3ref2
	.byte $48, $b4, $08, $ad, $14, $ad, $13, $ad, $0d, $ad, $10, $ad, $17, $ad
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song3ref88:
	.byte $86, $14, $89, $90, $08, $89, $84, $1b, $89, $90, $08, $89, $84, $17, $89, $90, $08, $89, $88, $14, $89, $90, $08, $89
	.byte $86, $16, $89, $90, $08, $89, $84, $17, $89, $90, $08, $89, $88, $13, $89, $90, $07, $89, $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
@song3ref138:
	.byte $48, $86, $14, $89, $8e, $08, $89, $84, $1b, $89, $8e, $08, $89, $84, $17, $89, $8e, $08, $89, $88, $14, $89, $8e, $08
	.byte $89, $86, $16, $89, $8e, $08, $89, $84, $17, $89, $88, $17, $89, $1b, $89, $22, $89, $48, $86, $23, $89, $8e, $17, $89
	.byte $1b, $89, $17, $89, $86, $25, $89, $8e, $16, $89, $19, $89, $16, $89, $86, $27, $89, $8e, $15, $89, $1b, $89, $15, $89
	.byte $86, $28, $89, $8e, $12, $89, $1c, $89, $12, $89, $84, $2a, $89, $8e, $17, $89, $1b, $89, $17, $89, $84, $2b, $89, $8e
	.byte $1b, $89, $16, $89, $13, $89, $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48, $b4, $14, $ad, $13, $ad, $12, $ad, $11, $ad, $10, $ad, $13, $ad, $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $48
	.byte $41, $1c
	.word @song3ref88
	.byte $41, $4c
	.word @song3ref138
	.byte $48, $b8
@song3ref303:
	.byte $2c, $87, $45, $23, $87, $45, $20, $87, $45, $23, $87, $45, $2c, $87, $45, $23, $87, $45, $20, $87, $45, $23, $87, $45
	.byte $2b, $87, $45, $22, $87, $45, $1f, $87, $45, $22, $87, $45, $2b, $87, $45, $22, $87, $45, $1f, $87, $45, $22, $87, $45
	.byte $48, $28, $87, $45, $23, $87, $45, $1e, $87, $45, $23, $87, $45, $28, $87, $45, $23, $87, $45, $1e, $87, $45, $23, $87
	.byte $45, $28, $87, $45, $24, $87, $45, $1e, $87, $45, $24, $87, $45, $28, $87, $45, $24, $87, $45, $1e, $87, $45, $24, $87
	.byte $45, $48, $28, $87, $45, $25, $87, $45, $22, $87, $45, $25, $87, $45, $28, $87, $45, $25, $87, $45, $22, $87, $45, $25
	.byte $87, $45, $2a, $87, $45, $23, $87, $45, $1e, $87, $45, $23, $87, $45, $2a, $87, $45, $23, $87, $45, $1e, $87, $45, $23
	.byte $87, $45, $48, $2c, $87, $45, $27, $87, $45, $23, $87, $45, $27, $87, $45, $2c, $87, $45, $27, $87, $45, $23, $87, $45
	.byte $27, $87, $45, $2b, $87, $45, $27, $87, $45, $22, $87, $45, $27, $87, $45, $2b, $87, $45, $27, $87, $45, $22, $87, $45
	.byte $27, $87, $45, $48
	.byte $41, $9c
	.word @song3ref303
	.byte $33, $87, $45, $27, $87, $45, $23, $87, $45, $27, $87, $45, $2e, $87, $45, $27, $87, $45, $22, $87, $45, $27, $87, $45
	.byte $33, $87, $45, $27, $87, $45, $22, $87, $45, $27, $87, $45, $42
	.word @song3ch0loop
@song3ch1:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch1loop:
	.byte $4e, $fc, $8e
@song3ref556:
	.byte $08, $93, $45, $87, $00, $81, $08, $93, $45, $87, $00, $81, $08, $93, $45, $87, $00, $81, $08, $93, $45, $87, $00, $81
	.byte $07, $83, $00, $83, $07, $83, $00, $83, $4e, $fc
	.byte $41, $20
	.word @song3ref556
@song3ref593:
	.byte $08, $93, $45, $a4, $17, $89, $8e, $08, $89, $a4, $14, $89, $00, $89, $8e, $0f, $93, $45, $a4, $13, $89, $8e, $08, $89
	.byte $a4, $14, $89, $00, $89, $0f, $89, $8e, $07, $83, $00, $83
	.byte $41, $1c
	.word @song3ref593
	.byte $40, $0b, $87, $00, $40, $0b, $87, $00, $40, $0b, $93, $00, $40, $0a, $87, $00, $40, $0a, $87, $00, $40, $0a, $93, $00
	.byte $09, $87, $00, $09, $87, $00, $09, $93, $00, $06, $87, $00, $06, $87, $00, $06, $93, $00, $04, $87, $00, $04, $87, $00
	.byte $04, $93, $00, $03, $87, $00, $03, $87, $00, $03, $93, $00
@song3ref692:
	.byte $17, $83, $43, $08, $83, $17, $83, $00, $83, $43, $08, $89, $17, $83, $43, $08, $83, $17, $83, $00, $83, $43, $08, $89
	.byte $41, $14
	.word @song3ref692
	.byte $17, $83, $43, $07, $83, $17, $83, $43, $07, $83
	.byte $41, $14
	.word @song3ref692
	.byte $41, $14
	.word @song3ref692
	.byte $17, $83, $43, $07, $83, $17, $83, $43, $07, $83
	.byte $41, $14
	.word @song3ref692
	.byte $41, $14
	.word @song3ref692
	.byte $17, $83, $43, $07, $83, $17, $83, $43, $07, $83
	.byte $41, $14
	.word @song3ref692
	.byte $41, $14
	.word @song3ref692
	.byte $17, $83, $43, $07, $83, $17
@song3ref773:
	.byte $83, $43, $07, $83, $08, $89, $1b, $83, $00, $83, $90, $17, $89, $8e, $08, $89, $1b, $83, $00, $83, $08, $83, $00, $83
	.byte $08, $89, $1b, $83, $00, $83, $90, $13, $89, $8e, $08, $89, $1b, $83, $00, $83, $08, $89, $00, $83, $43, $07, $83, $1b
	.byte $41, $2a
	.word @song3ref773
	.byte $41, $2a
	.word @song3ref773
	.byte $41, $2a
	.word @song3ref773
	.byte $83, $43, $07, $83, $0f, $ad, $0e, $ad, $0d, $ad, $0c, $ad, $0b, $ad, $07, $ad
	.byte $41, $1c
	.word @song3ref593
	.byte $41, $1c
	.word @song3ref593
	.byte $08, $93, $45, $86, $17, $89, $8e, $08, $89, $84, $14, $89, $00, $89, $8e, $08, $89, $88, $0f, $89, $13, $89, $4e, $fd
	.byte $8e, $08, $89, $84, $14, $89, $00, $89, $86, $0f, $89, $8e, $07, $83, $00, $83, $08, $93, $45, $86, $17, $89, $8e, $08
	.byte $89, $84, $14, $89, $00, $89, $8e, $08, $89, $88, $0f, $89, $4e, $ff, $13, $89, $8e, $08, $89, $84, $14, $89, $14, $89
	.byte $86, $17, $89, $1e, $89, $1e, $89, $8e, $40, $0b, $87, $00, $40, $0b, $93, $00, $86, $1c, $89, $8e, $40, $0a, $87, $00
	.byte $40, $0a, $93, $00, $86, $23, $89, $8e, $09, $87, $00, $09, $93, $00, $86, $24, $89, $8e, $06, $87, $00, $06, $93, $00
	.byte $84, $23, $89, $8e, $04, $87, $00, $04, $93, $00, $88, $22, $89, $8e, $03, $87, $00, $03, $93
@song3ref991:
	.byte $00, $4e, $fd, $08, $87, $00, $08, $87, $00, $08, $93, $00, $08, $87, $00, $08, $87, $00, $08, $93, $00, $0a, $87, $00
	.byte $0a, $87, $00, $40, $0a, $93, $00, $0a, $87, $00, $0a, $87, $00, $0a, $93, $00, $40, $0b, $9f, $00, $0b, $87, $00, $0b
	.byte $87, $00, $0b, $87, $00, $40, $0b, $93, $00, $10, $87, $00, $04, $93, $00, $0f, $87, $00, $0f, $87, $00, $0f, $9f, $00
	.byte $01, $87, $00, $01, $87, $00, $0d, $87, $00, $01, $87, $00, $01, $87, $00, $0d, $87, $00, $0d, $87, $00, $01, $87, $00
	.byte $40, $0b, $87, $00, $40, $0b, $87, $00, $0b, $93, $00, $40, $0b, $87, $00, $0b, $93, $00, $40, $0b, $87, $00, $40, $0b
	.byte $87, $00, $0b, $93, $00, $0b, $87, $00, $0b, $93, $00, $0b, $87, $00, $0b, $87, $00, $0a, $87, $00, $40, $0a, $93, $00
	.byte $0a, $87, $00, $07, $93, $00, $07, $87, $00, $07, $87
	.byte $41, $6d
	.word @song3ref991
	.byte $0b, $87, $00, $0b, $93, $00, $08, $87, $00, $08, $93, $00, $08, $87, $00, $08, $87, $00, $0a, $87, $00, $0a, $93, $00
	.byte $07, $87, $00, $07, $93, $00, $07, $87, $00, $07, $87, $00, $42
	.word @song3ch1loop
@song3ch2:
@song3ref1188:
	.byte $ac
@song3ref1189:
	.byte $14, $95, $00, $89, $14, $95, $00, $89, $14, $95, $00, $89, $14, $95, $00, $89, $13, $85, $00, $81, $13, $85, $00, $81
	.byte $41, $18
	.word @song3ref1189
	.byte $41, $18
	.word @song3ref1189
	.byte $41, $18
	.word @song3ref1189
	.byte $14, $95, $20, $95, $0b, $95, $17, $95, $0a, $95, $16, $95, $0d, $95, $19, $95, $10, $95, $1c, $95, $0b, $95, $17, $95
@song3ch2loop:
@song3ref1247:
	.byte $ae
@song3ref1248:
	.byte $08, $87, $00, $08, $9f, $00, $08, $9f, $00, $08, $9f, $00, $08, $93, $00, $07, $89, $13, $89
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $ac, $27, $ad, $2f, $ad, $2d, $ad, $28, $ad, $2c, $ad, $2b, $ad, $b2, $2c, $ff, $8d, $43, $50, $48, $38, $20, $95
	.byte $41, $18
	.word @song3ref1188
	.byte $41, $18
	.word @song3ref1189
	.byte $41, $18
	.word @song3ref1189
	.byte $41, $13
	.word @song3ref1247
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $ac, $14, $95, $2f, $89, $2f, $89, $13, $95, $26, $89, $26, $89, $12, $95, $2d, $89, $2d, $89, $11, $95, $2c, $89, $2c
	.byte $89, $10, $95, $2b, $89, $2b, $89, $13, $95, $2b, $89, $2b, $89
	.byte $41, $13
	.word @song3ref1247
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $41, $13
	.word @song3ref1248
	.byte $ac, $27, $ad, $2f, $ad, $2d, $ad, $28, $ad, $2c, $ad, $2b, $ad, $ae
@song3ref1383:
	.byte $14, $a1, $14, $a1, $14, $95, $16, $a1, $16, $a1, $16, $95, $17, $a1, $17, $a1, $17, $95, $18, $a1, $18, $a1, $18, $95
	.byte $19, $a1, $25, $89, $19, $95, $19, $95, $17, $a1, $17, $a1, $1a, $95, $1b, $a1, $1b, $a1, $1b, $95, $27, $a1, $27, $a1
	.byte $1b, $95
	.byte $41, $32
	.word @song3ref1383
	.byte $42
	.word @song3ch2loop
@song3ch3:
	.byte $82
@song3ref1440:
	.byte $34, $89, $00, $95, $34, $89, $00, $95, $34, $89, $00, $95, $34, $89, $00, $95, $34, $89, $34, $89
	.byte $41, $14
	.word @song3ref1440
@song3ref1463:
	.byte $34, $89, $80, $2f, $83, $00, $83, $2f, $83, $00, $83
@song3ref1474:
	.byte $82, $34, $89, $80, $2f, $83, $00, $83, $2f, $83, $00, $83, $82, $34, $89, $80, $2f
@song3ref1491:
	.byte $83, $00, $83, $2f, $83, $00, $83, $82, $34, $89, $80, $2f, $85, $2f, $85, $2f, $85, $82, $34, $89, $34, $89
	.byte $41, $2a
	.word @song3ref1463
@song3ref1516:
	.byte $34, $89, $80, $2f, $89, $aa, $2d, $89, $80, $2f, $83, $2f, $83, $82, $34, $89, $80, $2f, $89, $aa, $2d, $89, $80, $2f
	.byte $83, $2f, $83, $82, $34, $83, $80, $2f, $83, $2f, $83, $2f, $83, $aa, $2d, $89, $80, $2f, $89, $82, $34, $89, $80, $2f
	.byte $83, $00, $83, $2f, $83, $00, $83, $2f, $83, $00, $83, $82, $34, $89, $80, $2f, $89, $aa, $2d, $89, $2d, $89, $2d, $89
	.byte $80, $2f, $89, $82, $34, $89, $34, $89
@song3ch3loop:
	.byte $41, $17
	.word @song3ref1474
	.byte $41, $13
	.word @song3ref1491
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
@song3ref1612:
	.byte $92, $34, $89, $8c, $31, $89, $a8, $2d, $89, $8c, $31, $83, $31, $83, $92, $34, $89, $8c, $31, $89, $a8, $2d, $89, $8c
	.byte $31, $83, $31, $83, $92, $34, $83, $8c, $31, $83, $31, $83, $31, $83, $a8, $2d, $89, $8c, $31, $89, $92, $34, $89, $8c
	.byte $31, $83, $00, $83, $31, $83, $00, $83, $31, $83, $00, $83, $92, $34, $89, $8c, $31, $89, $a8, $2d, $89, $2d, $89, $2d
	.byte $89, $8c, $31, $89, $92, $34, $89, $34, $89, $34, $89
@song3ref1695:
	.byte $8c, $30, $83, $00, $83, $30, $83, $00, $83
@song3ref1704:
	.byte $92, $34, $89, $8c, $30, $83, $00, $83, $30, $83, $00, $83, $92, $34, $89, $8c, $30
@song3ref1721:
	.byte $83, $00, $83, $30, $83, $00, $83, $92, $34, $89, $8c, $30, $85, $30, $85, $30, $85, $92, $34, $89, $34, $89
	.byte $41, $17
	.word @song3ref1474
	.byte $41, $13
	.word @song3ref1491
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $3e
	.word @song3ref1516
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $2a
	.word @song3ref1463
	.byte $41, $68
	.word @song3ref1612
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $a8, $2d, $89, $2d, $89
	.byte $41, $17
	.word @song3ref1704
	.byte $41, $13
	.word @song3ref1721
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $41, $1f
	.word @song3ref1695
	.byte $41, $13
	.word @song3ref1721
	.byte $a8, $2d, $89, $2d, $89, $42
	.word @song3ch3loop
@song3ch4:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch4loop:
	.byte $52, $80
@song3ref1854:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $01, $ad, $02, $ad, $03, $ad, $04, $ad, $01, $ad, $05, $ad, $01, $ad, $01, $ad
	.byte $01, $ad, $00, $95, $52, $80, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
	.byte $41, $18
	.word @song3ref1854
@song3ref1904:
	.byte $02, $ad, $02, $ad, $04, $ad, $04, $ad, $03, $ad, $03, $ad, $02, $ad, $02, $ad, $04, $ad, $04, $ad, $01, $ad, $01, $ad
	.byte $05, $ad, $05, $ab, $00, $01, $ad, $01, $ad
	.byte $41, $1d
	.word @song3ref1904
	.byte $42
	.word @song3ch4loop
@song3ch5:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch5loop:
@song3ref1955:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7
	.byte $41, $13
	.word @song3ref1955
@song3ref1977:
	.byte $ff, $ff, $9f, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	.word @song3ch5loop
@song3ch6:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch6loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch6loop
@song3ch7:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch7loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch7loop
@song3ch8:
	.byte $82
@song3ref2048:
	.byte $14, $ff, $a5, $ff, $a7, $ff, $a7, $ff, $a7, $20, $89, $27, $89, $2c, $89, $2f, $89, $2c, $89, $33, $89, $38, $89, $3b
	.byte $89, $2b, $89, $32, $89, $37, $89, $3a, $89, $25, $89, $2c, $89, $31, $89, $34, $89, $28, $89, $2f, $89, $34, $89, $37
	.byte $89, $2f, $89, $36, $89, $3e, $89, $3b, $89
@song3ch8loop:
@song3ref2106:
	.byte $20, $89, $00, $89, $27, $89, $00, $89, $23, $89, $00, $89, $20, $89, $00, $89, $22, $89, $00, $89, $23, $89, $00, $89
	.byte $1f, $89, $00, $89
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $81, $8a, $20, $ab, $43, $1c, $ad, $43, $1b, $ad, $43, $1c, $ad, $43, $20, $ad, $43, $1f, $ad, $82
@song3ref2163:
	.byte $2f, $83
@song3ref2165:
	.byte $00, $83, $2f, $83, $00, $8f, $2f, $83, $00, $83, $2f, $83, $00, $8f, $2f, $83, $00, $83, $2f, $83, $00, $8f, $2f, $83
	.byte $00, $83, $2f, $83, $00, $8f, $2f, $83, $00, $83, $2f, $83, $00, $83
	.byte $41, $28
	.word @song3ref2163
	.byte $41, $28
	.word @song3ref2163
	.byte $41, $28
	.word @song3ref2163
@song3ref2212:
	.byte $2c, $83, $00, $83, $2c, $83, $00, $8f, $2c, $83, $00, $83, $2c, $83, $00, $8f, $2c, $83, $00, $83, $2c, $83, $00, $8f
	.byte $2c, $83, $00, $83, $2c, $83, $00, $8f, $2b, $83, $00, $83, $2b, $83, $00, $83
	.byte $41, $28
	.word @song3ref2212
	.byte $41, $28
	.word @song3ref2212
	.byte $41, $28
	.word @song3ref2212
	.byte $2c, $ad, $2b, $ad, $2a, $ad, $30, $ad, $2f, $ad, $32, $ad
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $81, $8a, $20, $ab, $43, $1c, $ad, $43, $1b, $ad, $43, $1c, $ad, $43, $20, $ad, $43, $1f, $ad, $00, $82, $14, $db
@song3ref2308:
	.byte $16, $dd, $17, $dd, $18, $dd, $19, $dd, $17, $dd, $17, $dd, $16, $dd, $14, $dd, $16, $dd, $17, $dd, $18, $dd, $19, $dd
	.byte $17, $dd, $17, $dd, $16, $dd, $42
	.word @song3ch8loop
@song3ch9:
	.byte $86
	.byte $41, $39
	.word @song3ref2048
@song3ch9loop:
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
@song3ref2352:
	.byte $1b, $89, $00, $89, $23, $89, $00, $89, $20, $89, $00, $89, $1b, $89, $00, $89, $1f, $89, $00, $89, $20, $89, $00, $89
	.byte $1b, $89, $00, $89
	.byte $41, $1c
	.word @song3ref2352
	.byte $84, $1b, $ad, $43, $19, $ad, $43, $18, $ad, $43, $17, $ad, $43, $1b, $ad, $43, $1b, $ab, $86, $2f, $85
	.byte $41, $26
	.word @song3ref2165
	.byte $41, $28
	.word @song3ref2163
	.byte $41, $28
	.word @song3ref2163
	.byte $41, $28
	.word @song3ref2163
@song3ref2416:
	.byte $33, $83, $00, $83, $33, $83, $00, $8f, $33, $83, $00, $83, $33, $83, $00, $8f, $33, $83, $00, $83, $33, $83, $00, $8f
	.byte $33, $83, $00, $83, $33, $83, $00, $8f, $33, $83, $00, $83, $33, $83, $00, $83
	.byte $41, $28
	.word @song3ref2416
	.byte $41, $28
	.word @song3ref2416
	.byte $41, $28
	.word @song3ref2416
	.byte $33, $8d, $2f, $8d, $33, $8d, $32, $8d, $31, $8d, $2e, $8d, $2d, $8d, $30, $8d, $31, $8d, $30, $8d, $2d, $8d, $2a, $8d
	.byte $28, $8d, $2b, $8d, $2f, $8d, $37, $8d, $36, $8d, $37, $8d
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2106
	.byte $41, $1c
	.word @song3ref2352
	.byte $41, $1c
	.word @song3ref2352
	.byte $84, $1b, $ad, $43, $19, $ad, $43, $18, $ad, $43, $17, $ad, $43, $1b, $ad, $43, $1b, $ab, $86, $14, $df
	.byte $41, $1e
	.word @song3ref2308
	.byte $42
	.word @song3ch9loop
@song3ch10:
	.byte $90, $08, $ff, $8d, $43, $07, $95, $43, $08, $ff, $8d, $43, $07, $95, $43, $08, $ff, $8d, $43, $07, $95, $43, $08, $ff
	.byte $8d, $43, $07, $95, $80, $14, $95, $20, $89, $20, $89, $0b, $95, $17, $89, $17, $89, $0a, $95, $16, $89, $16, $89, $0d
	.byte $95, $19, $89, $19, $89, $10, $95, $1c, $89, $1c, $89, $0b, $95, $17, $89, $17, $89
@song3ch10loop:
	.byte $80
@song3ref2607:
	.byte $14, $95
@song3ref2609:
	.byte $00, $89, $14, $95, $00, $89, $14, $95, $00, $89, $14, $95, $00, $89, $13, $89, $13, $89
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $13
	.word @song3ref2607
	.byte $87, $8c, $17, $af, $43, $16, $ad, $43, $15, $ad, $43, $12, $ad, $43, $17, $ad, $43, $16, $ad, $00, $80, $14, $93
	.byte $41, $12
	.word @song3ref2609
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $14, $95, $20, $95, $13, $95, $1f, $95, $12, $95, $1e, $95, $11, $95, $1d, $95, $10, $95, $1c, $95, $13, $95, $1f, $95
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $14
	.word @song3ref2607
	.byte $41, $13
	.word @song3ref2607
	.byte $87, $8c, $17, $af, $43, $16, $ad, $43, $15, $ad, $43, $12, $ad, $43, $17, $ad, $43, $16, $ad, $98
@song3ref2739:
	.byte $38, $89, $2f, $89, $2c, $89, $2f, $89, $38, $89, $2f, $89, $2c, $89, $2f, $89, $37, $89, $2e, $89, $2b, $89, $2e, $89
	.byte $37, $89, $2e, $89, $2b, $89, $2e, $89, $34, $89, $2f, $89, $2a, $89, $2f, $89, $34, $89, $2f, $89, $2a, $89, $2f, $89
	.byte $34, $89, $30, $89, $2a, $89, $30, $89, $34, $89, $30, $89, $2a, $89, $30, $89, $34, $89, $31, $89, $2e, $89, $31, $89
	.byte $34, $89, $31, $89, $2e, $89, $31, $89, $36, $89, $2f, $89, $2a, $89, $2f, $89, $36, $89, $2f, $89, $2a, $89, $2f, $89
	.byte $38, $89, $33, $89, $2f, $89, $33, $89, $38, $89, $33, $89, $2f, $89, $33, $89, $37, $89, $33, $89, $2e, $89, $33, $89
	.byte $37, $89, $33, $89, $2e, $89, $33, $89
	.byte $41, $68
	.word @song3ref2739
	.byte $3f, $89, $33, $89, $2f, $89, $33, $89, $3a, $89, $33, $89, $2e, $89, $33, $89, $3f, $89, $33, $89, $2e, $89, $33, $89
	.byte $42
	.word @song3ch10loop
@song3ch11:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch11loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch11loop
@song3ch12:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch12loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch12loop
@song3ch13:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch13loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch13loop
@song3ch14:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch14loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch14loop
@song3ch15:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch15loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch15loop
@song3ch16:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch16loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch16loop
@song3ch17:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch17loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch17loop
@song3ch18:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch18loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch18loop
@song3ch19:
	.byte $ff, $a7, $ff, $a7, $ff, $a7, $ff, $a7, $ff, $ff, $9f
@song3ch19loop:
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1955
	.byte $41, $13
	.word @song3ref1977
	.byte $42
	.word @song3ch19loop
